scripts/install.sh

chore: add automated release install script

---

docs/commands/rhoas_login.adoc
pkg/connection/keycloak_connection.go

fix: update mas-sso url

---

pkg/cmd/kafka/topic/create/create.go
pkg/cmd/kafka/topic/update/update.go
pkg/kafka/topic/util.go
pkg/kafka/topic/util_test.go

Resolves #555 
1. Create a topic and update a topic, be sure to provide a value for `retention.ms` to exercise this change.

refactor(topic): refactor how config entries get created

---

pkg/cmd/login/login.go

style: remove unused option

---

.github/workflows/release.yml

ci: embed static assets before releasing

---

pkg/cmd/cluster/connect/connect.go
pkg/cmd/cluster/status/status.go
pkg/cmd/completion/bash/bash.go
pkg/cmd/completion/completion.go
pkg/cmd/completion/fish/fish.go
pkg/cmd/completion/zsh/zsh.go
pkg/cmd/kafka/consumergroup/list/list.go
pkg/cmd/kafka/kafka.go
pkg/cmd/kafka/list/list.go
pkg/cmd/kafka/topic/delete/delete.go
pkg/cmd/kafka/topic/describe/describe.go
pkg/cmd/kafka/topic/list/list.go
pkg/cmd/kafka/topic/update/update.go
pkg/cmd/login/login.go
pkg/cmd/logout/logout.go
pkg/cmd/serviceaccount/delete/delete.go
pkg/cmd/serviceaccount/describe/describe.go
pkg/cmd/serviceaccount/list/list.go
pkg/cmd/status/status.go
pkg/cmd/version/version.go
pkg/cmd/whoami/whoami.go

fix: set explicit valid argument number for command

---

.github/pull_request_template.md

This PR simplifies the pull request template.

chore: simplify PR template

---

pkg/cmd/kafka/create/create.go

Fixes a pointer error when the ID is nil.

fix: pointer error

---

pkg/cmd/kafka/delete/delete.go
pkg/cmd/kafka/describe/describe.go
pkg/cmd/kafka/kafka.go
pkg/cmd/kafka/topic/delete/delete.go
pkg/cmd/kafka/topic/describe/describe.go
pkg/cmd/kafka/topic/update/update.go
pkg/cmd/kafka/use/use.go
pkg/cmdutil/cmdutil.go

Closes #554 
1. Re-install the Bash completion scripts for good measure.
2. Ensure you are in a Bash shell.
3. Run `rhoas kafka topic describe <TAB>` to let the dynamic auto completion function show the list of topics available.

fix(completion): fix dynamic completions for Bash

---

pkg/cmd/kafka/use/use.go

fix: return nil when no Kafka was selected

---

locales/cmd/kafka/topic/update/active.en.toml

rep factor

---

.chglog/CHANGELOG.tpl.md
.chglog/RELEASE.tpl.md
.github/workflows/changelog.yml

ci: generate a CHANGELOG on push to main

---

.github/workflows/release.yml

ci(release): generate release notes

---

.gitignore

chore: delete package-lock from mock directory

---

.chglog/RELEASE.tpl.md
.chglog/config.yml
.github/workflows/release.yml

ci(release): conditionally generate release notes

---

.chglog/config.yml
.github/workflows/gobuild.yml

chore: make "v" release prefix optional

---

.gitattributes

@craicoverflow as agreed I need to land this to master in order to have some form of review in the PR we are making 
Technically we could ignore the entire folder but that will exclute 2 files that are made by us

chore: new api PR ignore

---

pkg/cmd/kafka/consumergroup/list/list.go
pkg/cmd/kafka/topic/list/list.go
pkg/httputil/logging_round_tripper.go

fix: misformatted error message

---

go.mod
go.sum

Removed unused dependency [afero](github.com/spf13/afero)

chore: remove unused dependency afero

---

.github/workflows/release.yml

ci: fix missing tag in if statement

---

.github/workflows/release.yml

ci: fix incorrect set-output

---

.github/workflows/release.yml

ci: remove test step

---

.github/workflows/release.yml

ci: fix conditional check

---

scripts/install.sh

chore: make install script backwards compatible

---

pkg/kafka/topic/validators.go
pkg/kafka/topic/validators_test.go

Closes #654 
1. Run the command to interactively create a kafka topic
```
go run ./cmd/rhoas kafka topic create
```
2. `kafka.k` should be valid and accepted whereas `.` and `..` should be rejected.

fix(kafka topic): update regexp for topic name

---

.github/pull_request_template.md
pkg/cmd/kafka/create/create.go
pkg/cmd/serviceaccount/create/create.go
pkg/kafka/kafka_util.go
pkg/localize/locales/en/cmd/kafka_create.en.toml

Closes #693, #694, #695
1. Do x
2. Do y

fix: minor bug fixes and validations

---

CONTRIBUTING.md

Update instructions in `CONTRIBUTING.md` to create a new release.

docs(contributing): update release steps

---

pkg/cmd/kafka/create/create.go
pkg/cmd/kafka/topic/create/create.go
pkg/cmd/kafka/topic/list/list.go
pkg/cmd/kafka/topic/update/update.go
pkg/cmd/serviceaccount/create/create.go
pkg/kafka/kafka_util.go
pkg/kafka/kafka_util_test.go
pkg/kafka/topic/validators.go
pkg/kafka/topic/validators_test.go
pkg/localize/locales/en/cmd/kafka_topic_common.en.toml
pkg/serviceaccount/validation/validation.go
pkg/serviceaccount/validation/validation_test.go

Localization has been added to validation methods as needed.
Closes #692
The PR affects the following commands:
`rhoas kafka create`
`rhoas kafka topic create`
`rhoas kafka topic list --search <search input>`
`rhoas kafka topic update`
`rhoas kafka serviceaccount create`
- [] Bug fix (non-breaking change which fixes an issue)

refactor(localization): localize validation methods

---

.github/workflows/release.yml
pkg/cmd/kafka/consumergroup/list/list.go
pkg/cmd/kafka/create/create.go
pkg/cmd/kafka/list/list.go
pkg/cmd/kafka/topic/create/create.go
pkg/cmd/kafka/topic/list/list.go
pkg/cmd/kafka/topic/update/update.go
pkg/cmd/login/login.go
pkg/cmd/serviceaccount/create/create.go
pkg/cmd/serviceaccount/delete/delete.go
pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go
pkg/connection/keycloak_connection.go
pkg/kafka/kafka_util.go
pkg/kafka/kafka_util_test.go
pkg/kafka/kafkaerr/error.go
pkg/kafka/topic/validators.go
pkg/kafka/topic/validators_test.go
pkg/localize/locales/en/cmd/kafka_topic_common.en.toml
pkg/localize/locales/en/cmd/serviceaccount.en.toml
pkg/serviceaccount/validation/validation.go
pkg/serviceaccount/validation/validation_test.go

This PR merges the `develop` feature branch back to main

Merge 'develop' into main branch

---

CONTRIBUTING.md
pkg/localize/locales/en/cmd/registry_crud.en.toml

Follows up on https://github.com/redhat-developer/app-services-cli/pull/691
1. Build the CLI docs
2. View the generated output
- [ x] Documentation change
- [ x] Documentation added for the feature

chore: tidy up service registry cli docs

---

docs/commands/rhoas.adoc
docs/commands/rhoas_service-registry.adoc
docs/commands/rhoas_service-registry_create.adoc
docs/commands/rhoas_service-registry_delete.adoc
docs/commands/rhoas_service-registry_describe.adoc
docs/commands/rhoas_service-registry_list.adoc
docs/commands/rhoas_service-registry_use.adoc
go.mod
go.sum
pkg/cmd/registry/delete/delete.go
pkg/cmd/registry/list/list.go
pkg/localize/locales/en/cmd/registry_crud.en.toml
pkg/profile/profile.go

Fixes: https://github.com/redhat-developer/app-services-cli/issues/785

fix: cannot delete service registry by name

---

pkg/cmd/registry/list/list.go

#801 
```
OWNER                   STATUS  
--------- ----------------------- ---------------------------------------------------------------------------------------------------------------------- ----------------------- -------- 
5         ajay-test               https://service-registry-stage.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/t/c20f34a1-cf7e-43f0-abc4-4357fd9af2c1   apratap_kafka_devexp    ready   
6         testing-security-flow   https://service-registry-stage.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/t/fd9d0820-12f8-4a0b-a2be-03e3fc90da2c   carnalca                ready   
7         rama-test               https://service-registry-stage.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/t/7930767f-6d68-4282-8ebf-8428cc5aef0a   rpattnai_kafka_devexp   ready   
8 …
```

fix: add owner to registry list

---

go.mod
go.sum
pkg/cmd/root/validator_test.go

1. go mod tidy
2. go test ./pkg/cmd/root

chore: update charmil & validatorOptions

---

docs/commands/rhoas_cluster_status.adoc
pkg/localize/locales/en/cmd/cluster_status.en.toml

Update the status message for `rhoas cluster status`.

docs: update status message for 'rhoas cluster status'

---

docs/commands/rhoas_kafka_consumer-group_delete.adoc
docs/commands/rhoas_kafka_consumer-group_describe.adoc
pkg/localize/locales/en/cmd/kafka_consumergroup_delete.en.toml
pkg/localize/locales/en/cmd/kafka_consumergroup_describe.en.toml

Remove wrong examples for `consumer-group` describe and delete.
Closes #851

docs(kafka consumer-group): fix wrong examples

---

docs/commands/rhoas_cluster_connect.adoc
docs/commands/rhoas_login.adoc
internal/build/build.go

docs: replace "cloud.redhat.com" with new URL

---

.github/workflows/add-issue-to-project.yml

chore: add action to automate GitHub project board management

---

pkg/api/ams/amsclient/git_push.sh
scripts/check-docs.sh
scripts/generate-changelog.sh
scripts/install.sh
scripts/util/delete-service-accounts.sh
scripts/util/delete-user-kafkas.sh

https://disconnected.systems/blog/another-bash-strict-mode

chore: add strict mode to bash scripts

---

pkg/localize/locales/en/cluster_kubernetes.en.toml

Closes #899 
1. Do `rhoas cluster status`

fix: locale key err in cluster_kubernetes

---

Makefile

chore: remove githooks target, change default

---

docs/commands/rhoas_kafka_consumer-group.adoc
docs/commands/rhoas_kafka_topic_create.adoc
pkg/cmd/kafka/topic/describe/describe.go

fix: fixed an error message displayed for kafka topic describe

---

pkg/connection/keycloak_connection.go
pkg/connection/keycloak_util_test.go

Variable 'url' collides with imported package name

chore: variable 'url' collides with imported package name

---

pkg/cmd/cluster/connect/connect.go
pkg/cmd/cluster/status/status.go
pkg/cmd/kafka/create/create.go
pkg/cmd/kafka/delete/delete.go
pkg/cmd/kafka/describe/describe.go
pkg/cmd/kafka/list/list.go
pkg/cmd/kafka/update/update.go
pkg/cmd/kafka/use/use.go
pkg/cmd/logout/logout.go
pkg/cmd/registry/artifact/crud/list/list.go
pkg/cmd/registry/create/create.go
pkg/cmd/registry/delete/delete.go
pkg/cmd/registry/describe/describe.go
pkg/cmd/registry/list/list.go
pkg/cmd/registry/use/use.go
pkg/cmd/serviceaccount/create/create.go
pkg/cmd/serviceaccount/delete/delete.go
pkg/cmd/serviceaccount/describe/describe.go
pkg/cmd/serviceaccount/list/list.go
pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go
pkg/cmd/status/status.go
pkg/kafka/kafka_util.go

Variable 'connection' collides with imported package name

chore: variable 'connection' collides with imported package name

---

pkg/cmd/kafka/topic/list/list.go

Variable 'config' collides with imported package name

chore: variable 'config' collides with imported package name

---

pkg/cmd/kafka/use/use.go
pkg/connection/keycloak_connection.go
pkg/profile/profile.go
pkg/status/status.go

Code cleanup, declaration redundancy

chore: code cleanup, declaration redundancy

---

internal/build/build.go
pkg/auth/login/login.go
pkg/cmd/login/login.go
pkg/localize/locales/en/cmd/login.en.toml

feat: added a global timeout to the login command

---

pkg/cmd/registry/artifact/artifacts.go
pkg/cmd/registry/artifact/crud/create/create.go
pkg/cmd/registry/artifact/crud/delete/delete.go
pkg/cmd/registry/artifact/crud/get/get.go
pkg/cmd/registry/artifact/crud/list/list.go
pkg/cmd/registry/artifact/crud/update/update.go
pkg/cmd/registry/artifact/download/download.go
pkg/cmd/registry/artifact/metadata/get.go
pkg/cmd/registry/artifact/metadata/set.go
pkg/cmd/registry/artifact/versions/versions.go
pkg/localize/locales/en/cmd/artifact.en.toml

Let me know if we want that across entire fleet of commands

chore: remove i18n from use commands

---

pkg/cmd/registry/artifact/migrate/import.go

MIssed that change when rebasing

fix: remove mark flag required

---

cmd/rhoas/main.go
pkg/auth/login/login.go
pkg/cluster/kcManager.go
pkg/cluster/kubernetes_cluster.go
pkg/cluster/serviceBinding.go
pkg/cmd/kafka/consumergroup/resetoffset/reset_offset.go
pkg/cmd/kafka/create/create.go
pkg/cmd/kafka/delete/delete.go
pkg/cmd/kafka/use/use.go
pkg/cmd/login/login.go
pkg/cmd/logout/logout.go
pkg/cmd/registry/artifact/crud/get/get.go
pkg/cmd/registry/artifact/download/download.go
pkg/cmd/registry/artifact/metadata/get.go
pkg/cmd/registry/artifact/metadata/set.go
pkg/cmd/registry/artifact/versions/versions.go
pkg/cmd/registry/create/create.go
pkg/cmd/registry/delete/delete.go
pkg/cmd/registry/use/use.go
pkg/cmd/serviceaccount/create/create.go
pkg/cmd/serviceaccount/delete/delete.go
pkg/icon/icon.go

feat: emoji support for both error and success messages

---

pkg/cmd/kafka/consumergroup/describe/describe.go
pkg/kafka/kafka_util.go
pkg/localize/locales/en/cmd/kafka.en.toml

chore: updated strings according to MK UI

---

pkg/cmd/registry/artifact/artifacts.go
pkg/cmd/registry/artifact/state/state.go
pkg/cmd/registry/artifact/util/constants.go
pkg/localize/locales/en/cmd/artifact.en.toml

Last trivial command. Quick win to setup artifacts as deprecated etc.

Adding state command

---

pkg/cmd/registry/artifact/crud/create/create.go
pkg/cmd/registry/artifact/crud/delete/delete.go
pkg/cmd/registry/artifact/crud/get/get.go
pkg/cmd/registry/artifact/crud/update/update.go
pkg/cmd/registry/artifact/metadata/get.go
pkg/cmd/registry/artifact/metadata/set.go
pkg/cmd/registry/artifact/state/state.go
pkg/cmd/registry/artifact/versions/versions.go

chore: removed -a shortcut from artifacts commands

---

docs/commands/rhoas_kafka_describe.adoc
pkg/cmd/kafka/describe/describe.go
pkg/localize/locales/en/cmd/kafka.en.toml

feat: added an option to show bootstrap server host of the Kafka instance

---

pkg/cmd/kafka/consumergroup/describe/describe.go
pkg/cmd/kafka/consumergroup/list/list.go
pkg/cmd/kafka/create/create.go
pkg/cmd/kafka/describe/describe.go
pkg/cmd/kafka/list/list.go
pkg/cmd/kafka/topic/create/create.go
pkg/cmd/kafka/topic/describe/describe.go
pkg/cmd/kafka/topic/list/list.go
pkg/cmd/kafka/topic/update/update.go
pkg/cmd/registry/artifact/crud/list/list.go
pkg/cmd/registry/list/list.go
pkg/cmd/serviceaccount/describe/describe.go
pkg/cmd/serviceaccount/list/list.go
pkg/cmd/status/status.go
pkg/dump/dump.go

refactor: added dump print helper to all commands

---

pkg/cluster/kubernetes_cluster.go
pkg/cluster/serviceBinding.go
pkg/cmd/login/login.go
pkg/cmd/registry/artifact/metadata/set.go
pkg/cmd/registry/artifact/state/state.go
pkg/cmd/registry/artifact/versions/versions.go
pkg/kafka/consumergroup/validators.go
pkg/kafka/kafka_util.go
pkg/kafka/topic/validators.go
pkg/localize/locales/en/cmd/cluster_bind.en.toml
pkg/serviceaccount/validation/validation.go

Closes #1072. I've missed a few of them in the original commit that was merged.

refactor: changed the way some errors are localized

---

pkg/cmd/kafka/consumergroup/describe/describe.go
pkg/cmd/kafka/consumergroup/list/list.go
pkg/cmd/kafka/consumergroup/resetoffset/reset_offset.go
pkg/cmd/kafka/create/create.go
pkg/cmd/kafka/describe/describe.go
pkg/cmd/kafka/list/list.go
pkg/cmd/kafka/topic/create/create.go
pkg/cmd/kafka/topic/describe/describe.go
pkg/cmd/kafka/topic/list/list.go
pkg/cmd/kafka/topic/update/update.go
pkg/cmd/kafka/update/update.go
pkg/cmd/registry/artifact/crud/create/create.go
pkg/cmd/registry/artifact/crud/list/list.go
pkg/cmd/registry/artifact/crud/update/update.go
pkg/cmd/registry/artifact/metadata/get.go
pkg/cmd/registry/artifact/versions/versions.go
pkg/cmd/registry/create/create.go
pkg/cmd/registry/describe/describe.go
pkg/cmd/registry/list/list.go
pkg/cmd/serviceaccount/describe/describe.go
pkg/cmd/serviceaccount/list/list.go
pkg/cmd/status/status.go
pkg/dump/dump.go

refactor: made improvements in the dump package

---

pkg/cmd/cluster/bind/bind.go
pkg/cmd/cluster/connect/connect.go
pkg/cmd/kafka/use/use.go
pkg/kafka/interactive.go
pkg/localize/locales/en/cmd/kafka.en.toml

refactor: made improvements in kafka.InteractiveSelect() function

---

pkg/cmd/kafka/consumergroup/describe/describe.go
pkg/cmd/kafka/consumergroup/list/list.go
pkg/cmd/kafka/list/list.go
pkg/cmd/kafka/topic/list/list.go
pkg/cmd/registry/list/list.go
pkg/cmd/serviceaccount/list/list.go
pkg/kafka/interactive.go
pkg/serviceregistry/interactive.go

I've found a few more cases similar to what was described in #911, so I've fixed them.
Run commands affected by this change, such as
1. rhoas kafka use
2. rhoas kafka consumer-group describe
3. rhoas kafka list
4. rhoas kafka topic list
5. rhoas kafka consumer-group list

refactor: use make to create fixed size list

---

CHANGELOG.md
pkg/localize/locales/en/cmd/artifact.en.toml
pkg/localize/locales/en/cmd/registry_crud.en.toml

Docs review

---

pkg/kafka/topic/validators.go

```
rhoas kafka topic create
```

fix: interactive mode for creating topic returns error

---

pkg/cmd/registry/artifact/role/add/add.go

fix: set --role flag as required

---

docs/commands/rhoas.adoc
docs/commands/rhoas_service-registry.adoc
docs/commands/rhoas_service-registry_artifact.adoc
docs/commands/rhoas_service-registry_artifact_create.adoc
docs/commands/rhoas_service-registry_artifact_delete.adoc
docs/commands/rhoas_service-registry_artifact_download.adoc
docs/commands/rhoas_service-registry_artifact_export.adoc
docs/commands/rhoas_service-registry_artifact_get.adoc
docs/commands/rhoas_service-registry_artifact_import.adoc
docs/commands/rhoas_service-registry_artifact_list.adoc
docs/commands/rhoas_service-registry_artifact_metadata-get.adoc
docs/commands/rhoas_service-registry_artifact_metadata-set.adoc
docs/commands/rhoas_service-registry_artifact_state-set.adoc
docs/commands/rhoas_service-registry_artifact_update.adoc
docs/commands/rhoas_service-registry_artifact_versions.adoc
docs/commands/rhoas_service-registry_create.adoc
docs/commands/rhoas_service-registry_delete.adoc
docs/commands/rhoas_service-registry_describe.adoc
docs/commands/rhoas_service-registry_list.adoc
docs/commands/rhoas_service-registry_role.adoc
docs/commands/rhoas_service-registry_role_add.adoc
docs/commands/rhoas_service-registry_role_list.adoc
docs/commands/rhoas_service-registry_role_revoke.adoc
docs/commands/rhoas_service-registry_use.adoc
pkg/profile/profile.go

Change alpha to beta that will happen in the next release (with announcement)

fix: update devpreview to beta

---

docs/commands/rhoas_service-registry_artifact.adoc
docs/resources/avro-userInfo.json
pkg/localize/locales/en/cmd/artifact.en.toml

Add example avro schema that we can reference in the documentation of the registry commands

chore: add example avro schema

---

.goreleaser.yml

Closes #1152 
1. Run goreleaser, for example, `goreleaser release --snapshot`
2. Install generated RPM file on a target system

fix: corrected build path for rhoas executable

---

scripts/install.sh

Closes #1157 
1. Run `./scripts/install.sh` or `sh -x ./scripts/install.sh` if you want to see what script does
2. Verify that rhoas executable was successfully installed

fix: changed the source path for rhoas binary

---

pkg/localize/locales/en/cmd/kafka.en.toml
pkg/localize/locales/en/cmd/login.en.toml
pkg/localize/locales/en/cmd/registry_crud.en.toml
pkg/localize/locales/en/cmd/status.en.toml

Remove <> characters from strings

---

docs/commands/rhoas_login.adoc
docs/commands/rhoas_service-registry_delete.adoc
docs/commands/rhoas_service-registry_describe.adoc
docs/commands/rhoas_service-registry_use.adoc
docs/commands/rhoas_status.adoc
pkg/connection/keycloak_connection.go
pkg/service/status/status.go

fix: use pre-defined service status constant values

---

pkg/cmd/kafka/acl/list/list.go
pkg/kafka/acl/constants.go
pkg/localize/locales/en/cmd/acl.en.toml

Addressed review comments of #1173

fix(kafka acl): address review comments for list command

---

pkg/cmd/kafka/list/list.go
pkg/cmd/registry/list/list.go

Closes #1145 
1. Run `rhoas service-registry list`
2. Run `rhoas kafka list`

refactor: display current instance in list

---

USAGE_DATA.md
cmd/rhoas/main.go
go.mod
go.sum
internal/build/build.go
internal/config/type.go
pkg/cmd/root/root.go
pkg/localize/locales/en/common.en.toml
pkg/telemetry/sanitize.go
pkg/telemetry/segment.go
pkg/telemetry/telemetry.go
pkg/telemetry/user.go

https://developers.redhat.com/article/tool-data-collection
- Prevening help/completion commands to send data
- Preventing non TTY sessions 
- Adding env var along with config for internal team do disable telemetry.
__completion, help etc. should not send analytics

Telemetry implementation

---

cmd/rhoas/main.go
pkg/cmd/root/root.go

Analytics implementation broke debug logging. 
This PR fixes it

fix: enable debug logging for cli

---

pkg/localize/locales/en/cmd/acl.en.toml

docs: update help for kafka acl describe

---

Makefile
internal/build/build.go
pkg/ams/terms.go

Use production based json file.
use termsandconditions file for verification

fix: update terms spec url

---

pkg/localize/locales/en/cmd/acl.en.toml

docs: fix typo in kafka acl command help

---

docs/commands/rhoas_kafka_acl.adoc

chore: generate docs

---

docs/commands/rhoas_service-registry_artifact_create.adoc
pkg/cmd/registry/artifact/crud/create/create.go

Fixes https://github.com/redhat-developer/app-services-cli/issues/1318

fix: output format for create artifact cmd

---

docs/commands/rhoas.adoc
docs/commands/rhoas_service-registry.adoc
docs/commands/rhoas_service-registry_artifact.adoc
docs/commands/rhoas_service-registry_artifact_create.adoc
docs/commands/rhoas_service-registry_artifact_delete.adoc
docs/commands/rhoas_service-registry_artifact_download.adoc
docs/commands/rhoas_service-registry_artifact_export.adoc
docs/commands/rhoas_service-registry_artifact_get.adoc
docs/commands/rhoas_service-registry_artifact_import.adoc
docs/commands/rhoas_service-registry_artifact_list.adoc
docs/commands/rhoas_service-registry_artifact_metadata-get.adoc
docs/commands/rhoas_service-registry_artifact_metadata-set.adoc
docs/commands/rhoas_service-registry_artifact_state-set.adoc
docs/commands/rhoas_service-registry_artifact_update.adoc
docs/commands/rhoas_service-registry_artifact_versions.adoc
docs/commands/rhoas_service-registry_create.adoc
docs/commands/rhoas_service-registry_delete.adoc
docs/commands/rhoas_service-registry_describe.adoc
docs/commands/rhoas_service-registry_list.adoc
docs/commands/rhoas_service-registry_role.adoc
docs/commands/rhoas_service-registry_role_add.adoc
docs/commands/rhoas_service-registry_role_list.adoc
docs/commands/rhoas_service-registry_role_revoke.adoc
docs/commands/rhoas_service-registry_use.adoc
pkg/cmd/registry/registry.go

fix: remove dev preview

---

pkg/connection/keycloak_connection.go

1. `rhoas login`
2. then run whatever other command several times with `-v` flag, you will see SSO token is only refreshed when it expires. MAS SSO token seems to be refreshed very frequently, I guess that's because it expires very quickly.

refactor: refresh oauth tokens only when needed

---

pkg/localize/locales/en/cmd/acl.en.toml
pkg/localize/locales/en/cmd/cluster.en.toml
pkg/localize/locales/en/cmd/completion.en.toml
pkg/localize/locales/en/cmd/kafka.en.toml
pkg/localize/locales/en/cmd/kafka_consumergroup_reset_offset.toml
pkg/localize/locales/en/cmd/login.en.toml
pkg/localize/locales/en/cmd/logout.en.toml
pkg/localize/locales/en/cmd/root.en.en.toml
pkg/localize/locales/en/cmd/serviceaccount.en.toml
pkg/localize/locales/en/cmd/serviceaccount_create.en.toml
pkg/localize/locales/en/cmd/serviceaccount_delete.en.toml
pkg/localize/locales/en/cmd/serviceaccount_describe.en.toml
pkg/localize/locales/en/cmd/serviceaccount_list.en.toml
pkg/localize/locales/en/cmd/serviceaccount_reset_credentials.en.toml
pkg/localize/locales/en/cmd/status.en.toml
pkg/localize/locales/en/cmd/topic.en.toml
pkg/localize/locales/en/cmd/whoami.en.toml

I did a comprehensive review of the rhoas CLI command help and made edits to make the help more consistent and to add some additional detail for some of the features.
I did not review the Service Registry commands, but those can be done in a future PR.

Edits to command help

---

.vscode/launch.json
pkg/kafka/aclutil/enums.go
pkg/kafka/aclutil/util.go

This reverts commit 3c4f32223c0f506a11c4b254e36664c84e34e644 added in https://github.com/redhat-developer/app-services-cli/pull/1293.
Closes #1308 
Execute an ACL CRUD command, eg:
```shell
rhoas kafka acl create --permission allow --operation describe --cluster --all-accounts
```

revert: refactor: support different variations for resource types and operations

---

pkg/localize/locales/en/cmd/artifact.en.toml
pkg/localize/locales/en/cmd/registry_crud.en.toml
pkg/localize/locales/en/cmd/role.toml

Fixed minor formatting issues

---

README.md

1. The links modified in this PR should work

docs(readme): update links to guides repo

---

.vscode/extensions.json
CONTRIBUTING.md

Updated prerequisite sans the OpenApi generator

---

docs/commands/rhoas_service-registry_rule.md
docs/commands/rhoas_service-registry_rule_disable.md
docs/commands/rhoas_service-registry_rule_update.md
pkg/cmd/registry/artifact/crud/create/create.go
pkg/cmd/registry/artifact/crud/delete/delete.go
pkg/cmd/registry/artifact/crud/get/get.go
pkg/cmd/registry/artifact/crud/list/list.go
pkg/cmd/registry/artifact/crud/update/update.go
pkg/cmd/registry/artifact/download/download.go
pkg/cmd/registry/artifact/metadata/get.go
pkg/cmd/registry/artifact/metadata/set.go
pkg/cmd/registry/artifact/state/state.go
pkg/cmd/registry/artifact/util/constants.go
pkg/cmd/registry/artifact/util/util.go
pkg/cmd/registry/artifact/versions/versions.go
pkg/cmd/registry/registrycmdutil/constants.go
pkg/cmd/registry/rule/describe/describe.go
pkg/cmd/registry/rule/disable/disable.go
pkg/cmd/registry/rule/enable/enable.go
pkg/cmd/registry/rule/list/list.go
pkg/cmd/registry/rule/rule.go
pkg/cmd/registry/rule/rulecmdutil/flagset.go
pkg/cmd/registry/rule/update/update.go
pkg/core/localize/locales/en/cmd/artifact.en.toml
pkg/core/localize/locales/en/cmd/registry_crud.en.toml
pkg/core/localize/locales/en/cmd/rule.en.toml

Disable and update command for service-registry rules.
1. Run the following command to update config value of an enabled rule:
```
rhoas service-registry rule update --rule-type compatibility --config forward 
```
2. Run the following command to disable all global rules.
```
rhoas service-registry rule disable 
```

feat(service-registry rule): add disable and and update command

---

README.md

Type of change: Documentation change
The app-services-guides document path has been changed, update the README file to fix the broken links.

fix: Update README.md broken links

---

go.mod
go.sum
pkg/cmd/kafka/acl/delete/delete.go
pkg/cmd/kafka/acl/list/list.go
pkg/cmd/kafka/consumergroup/groupcmdutil/util.go
pkg/cmd/kafka/consumergroup/resetoffset/reset_offset.go
pkg/cmd/kafka/topic/create/create.go
pkg/cmd/kafka/topic/list/list.go
pkg/cmd/kafka/topic/topiccmdutil/util.go
pkg/cmd/kafka/topic/topiccmdutil/util_test.go
pkg/cmd/kafka/topic/update/update.go
pkg/shared/connection/api/defaultapi/default_client.go

I have verified all commands manually:
- Topics
- Consumer-Groups
- ACLs
Just minor changes were required.

fix: changes required for Kafka SDK update

---

.github/workflows/gobuild.yml
pkg/core/localize/locales/en/auth_token.en.toml

fix: include toml files in build

---

pkg/cmd/kafka/create/create.go
pkg/shared/accountmgmtutil/ams.go
pkg/shared/accountmgmtutil/quota.go
pkg/shared/remote/DynamicServiceConstants.go
pkg/shared/remote/service-constants.json

Adds extra steps to validate quota in AMS and introduces new developer quota

fix: validate AMS Quota Size before creating instance

---

README.md

docs: update intro in readme

---

docs/commands/rhoas_context.md
docs/commands/rhoas_context_create.md
docs/commands/rhoas_context_delete.md
docs/commands/rhoas_context_status.md
docs/commands/rhoas_context_use-service-registry.md
docs/commands/rhoas_context_use.md
docs/commands/rhoas_service-registry.md
docs/commands/rhoas_service-registry_use.md
pkg/core/localize/locales/en/cmd/context.en.toml
pkg/core/localize/locales/en/cmd/registry_crud.en.toml
pkg/shared/contextutil/util.go

fix: minor fixes for context

---

.github/workflows/release.yml

Fix unrecognized named-value in release workflow

ci(release): fix unrecognized named-value

---

pkg/cmd/kafka/create/create.go
pkg/core/localize/locales/en/cmd/kafka.en.toml

This is temporary change that disables region validation that will fail due to breaking change happening on the backend

fix: disable check for region

---

pkg/core/localize/locales/en/cmd/connectors.toml

Update description and example for `rhoas context update`

docs(connector update): change erroneous message

---

.github/workflows/gobuild.yml
pkg/core/localize/locales/en/cmd/context.en.toml

Builds are failing for golangci-lint

ci(lint): increase timeout

---

pkg/cmd/kafka/create/create.go
pkg/core/localize/locales/en/cmd/kafka.en.toml

fix(kafka create): change log messages

---

pkg/cmd/kafka/kafkacmdutil/topics_util.go
pkg/shared/kafkautil/interactive.go
pkg/shared/serviceregistryutil/interactive.go

fix(lint): response body must be closed

---

README.md

Add instructions in README to install and use the container image for RHOAS CLI.
Closes #1546

docs(README): mention container image in the README

---

pkg/cmd/kafka/create/api_validators.go
pkg/cmd/kafka/create/create.go
pkg/core/cmdutil/flagutil/flagset.go

Refactor sizes to introduce better handling:
- Dot not sent plan for trial kafka. There is no concept of plan for those 
- Fix bypas_ams_check flag breaking creation
- Rename flag to better reflect what it does.
-

Addressing feedback for instance sizes

---

WHATS_NEW.md

updated WHATS_NEW

---

docs/commands/rhoas_kafka_create.md
go.mod
go.sum
pkg/cmd/kafka/create/api_validators.go
pkg/cmd/kafka/create/completions.go
pkg/cmd/kafka/create/create.go
pkg/cmd/kafka/create/data.go
pkg/cmd/kafka/kafkacmdutil/kafka_util.go
pkg/core/localize/locales/en/cmd/kafka.en.toml
pkg/shared/accountmgmtutil/ams.go
pkg/shared/accountmgmtutil/api.go

Reverts redhat-developer/app-services-cli#1616

fix(kafka create): reduce number of calls made to AMS API

---

pkg/cmd/kafka/create/create.go
pkg/core/localize/locales/en/cmd/kafka.en.toml
pkg/shared/accountmgmtutil/ams.go

fix: billing model fixes

---

pkg/core/auth/login/login.go

1. Login to production
2. Try out registry instance artifact list
3. All should work
4. Login to stage
5. Run artifact list
6. All should work

fix: remove mas-sso tokens on login

---

WHATS_NEW.md

Add features added in `v0.46.0`

docs(whatsnew): add features of v0.46.0

---

pkg/cmd/kafka/create/create.go

This PR ensures that quota is not fetched when `--bypass-checks` flag is passed.
Interactive mode is disabled when `--bypass-checks` flag is passed.
Running the kafka create command in verbose mode shouldn't print Selected Quota object
```
./rhoas kafka create --name test-instance --bypass-checks --dry-run -v
```

fix(kafka create): skip quota fetch with bypass checks

---

docs/commands/rhoas_service-registry_artifact_list.md
pkg/cmd/registry/artifact/crud/list/list.go
pkg/core/localize/locales/en/cmd/artifact.en.toml

Closes #1649 
1. Create two artifacts in two different groups
2. List all artifacts in all groups and see if there are both of them
``rhoas service-registry artifact list --all-groups``

feat(service-registry): added --all-groups flag in artifact list command

---

pkg/cmd/connector/connector_type/list/list.go

Should now have a better search, still doesn't use ID .
1. Do x
2. Do y

fix: improved poor search in connector type list

---

docs/commands/rhoas_connector_type.md
docs/commands/rhoas_connector_type_describe.md
pkg/cmd/connector/connector_type/describe/describe.go
pkg/cmd/connector/connector_type/type.go
pkg/core/localize/locales/en/cmd/connectors.toml

Closes # 
1. Run `rhoas connector type describe --type=slack_source_0.1` should get valid output
2. Run `rhoas connector type describe --type=slack_random` should get error message of not found

Added connector type describe

---

pkg/cmd/token/token.go
pkg/cmd/whoami/whoami.go

Fixes: https://github.com/redhat-developer/app-services-cli/issues/1678

fix: refresh token before reading config

---

pkg/cmd/connector/connector_type/describe/describe.go
pkg/cmd/connector/connector_type/list/list.go
pkg/cmd/connector/connectorcmdutil/types_util.go
pkg/core/localize/locales/en/cmd/connectors.toml

- Adds search query helper for connectors API
- Adds suggestions for connector types
1. Use `rhoas connector type describe --type=` to get get full list of connector types possible

connector type improvements

---

WHATS_NEW.md

Adds information about new service registry setting command into WHATS_NEW.md

docs(whats-new): added service registry setting command

---

pkg/cmd/connector/namespace/namespace.go
pkg/cmd/connector/namespace/use/use.go
pkg/cmd/context/context.go
pkg/cmd/status/statusBuilder.go
pkg/core/localize/locales/en/cmd/context.en.toml
pkg/core/localize/locales/en/cmd/namespace.toml
pkg/core/servicecontext/type.go
pkg/shared/contextutil/util.go
pkg/shared/namespaceutil/api.go
pkg/shared/namespaceutil/interactive.go
pkg/shared/servicespec/services.go

Namespace in context

---

WHATS_NEW.md
pkg/core/localize/locales/en/cmd/setting.en.toml

Clarify admin and instance-only scope and add available Service Registry instance settings to CLI help, minor edits to `WHATS_NEW.md`

docs: describe available service registry instance settings, minor edits

---

go.mod
go.sum
pkg/cmd/connector/build/build.go

feat: updated json schema library

---

docs/commands/rhoas_service-registry.md
docs/commands/rhoas_service-registry_setting.md
docs/commands/rhoas_service-registry_setting_get.md
docs/commands/rhoas_service-registry_setting_list.md
docs/commands/rhoas_service-registry_setting_set.md
pkg/cmd/registry/setting/setting.go

docs: unhide service registry setting command, regenerate cli help doc

---

WHATS_NEW.md

Update `whats_new.md` with changes for `v0.48.0`.

docs(whatsnew): add entry for v0.48.0

---

pkg/cmd/connector/create/create.go

Connector create survey

---

docs/commands/rhoas_connector_namespace.md
docs/commands/rhoas_connector_namespace_use.md
docs/commands/rhoas_context.md
docs/commands/rhoas_context_set-namespace.md
go.mod
go.sum
pkg/cmd/connector/create/create.go

- Updates json library to v0.9.0
- Adds port nuumber to kafka URL in connector create

Create build fix

---

pkg/cmd/connector/create/create.go

fix: incorrect boostrap url for kafka in connector create

---

.github/workflows/release.yml

chore: bump version of go in release workflow

---

WHATS_NEW.md

Updated whats new to contain new connectors work
- [ x Documentation change

docs: updated WHATS NEW

---

.vscode/launch.json
pkg/cmd/connector/update/update.go
pkg/core/localize/locales/en/cmd/connectors.toml
pkg/core/localize/locales/en/cmd/kafka.en.toml
pkg/shared/connectorutil/interactive.go
pkg/shared/contextutil/util.go
pkg/shared/kafkautil/interactive.go
pkg/shared/namespaceutil/interactive.go

Connector edit

---

pkg/cmd/connector/update/update.go
pkg/core/localize/locales/en/cmd/connectors.toml

Adds prompt and help to change editor in connector update

feat: added info about changing editor in connector update

---

go.mod
go.sum
internal/build/build.go
pkg/cmd/connector/create/create.go
pkg/cmd/login/login.go
pkg/cmd/serviceaccount/create/create.go
pkg/cmd/serviceaccount/delete/delete.go
pkg/cmd/serviceaccount/describe/describe.go
pkg/cmd/serviceaccount/list/list.go
pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go
pkg/cmd/serviceaccount/svcaccountcmdutil/svcaccount_util.go
pkg/core/cmdutil/flagutil/completions.go
pkg/shared/cluster/connect.go
pkg/shared/connection/api/api.go
pkg/shared/connection/api/defaultapi/default_client.go
pkg/shared/connection/kcconnection/builder.go
pkg/shared/connection/kcconnection/keycloak_connection.go

Integrate `serviceaccount-sdk` with the RHOAS CLI
1. Build the CLI from the changes and try out the service account commands.
- ~~[ ] Distinguish between field "name" and "description" in `ServiceAccountData` object~~

chore: integrate service-account SDK

---

pkg/cmd/connector/connectorcmdutil/types_util.go

1. On main run `rhoas connector build --type=aws` should give suggestions of all types
2. On this branch run `rhoas connector build --type=aws` should give suggestions that start with the current input

feat: type flag suggestions now based on input

---

.vscode/launch.json
go.mod
go.sum
pkg/cmd/connector/build/build.go

feat: added error handler check in connector build

---

docs/commands/rhoas.md
docs/commands/rhoas_connector.md
docs/commands/rhoas_connector_build.md
docs/commands/rhoas_connector_cluster.md
docs/commands/rhoas_connector_cluster_create.md
docs/commands/rhoas_connector_cluster_delete.md
docs/commands/rhoas_connector_create.md
docs/commands/rhoas_connector_delete.md
docs/commands/rhoas_connector_describe.md
docs/commands/rhoas_connector_list.md
docs/commands/rhoas_connector_namespace.md
docs/commands/rhoas_connector_namespace_list.md
docs/commands/rhoas_connector_start.md
docs/commands/rhoas_connector_stop.md
docs/commands/rhoas_connector_type.md
docs/commands/rhoas_connector_type_describe.md
docs/commands/rhoas_connector_type_list.md
docs/commands/rhoas_connector_update.md
docs/commands/rhoas_connector_use.md
pkg/core/localize/locales/en/cmd/connectors.toml

WIP jc-1073-4 edits for connectors cli help text

---

go.mod
internal/build/build.go
pkg/cmd/connector/create/create.go
pkg/cmd/login/login.go
pkg/cmd/serviceaccount/create/create.go
pkg/cmd/serviceaccount/delete/delete.go
pkg/cmd/serviceaccount/describe/describe.go
pkg/cmd/serviceaccount/list/list.go
pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go
pkg/cmd/serviceaccount/svcaccountcmdutil/svcaccount_util.go
pkg/core/cmdutil/flagutil/completions.go
pkg/shared/cluster/connect.go
pkg/shared/connection/api/api.go
pkg/shared/connection/api/defaultapi/default_client.go
pkg/shared/connection/kcconnection/builder.go
pkg/shared/connection/kcconnection/keycloak_connection.go

Revert changes introduced in #1716.

fix: revert service accounts integration

---

docs/commands/rhoas_connector.md
docs/commands/rhoas_connector_build.md
docs/commands/rhoas_connector_cluster.md
docs/commands/rhoas_connector_cluster_delete.md
docs/commands/rhoas_connector_cluster_list.md
docs/commands/rhoas_connector_create.md
docs/commands/rhoas_connector_type.md
docs/commands/rhoas_connector_type_describe.md
docs/commands/rhoas_connector_type_list.md
docs/commands/rhoas_connector_update.md
pkg/core/localize/locales/en/cmd/connectors.toml

more edits to the rhoas connectors help text

docs: more edits to help text

---

WHATS_NEW.md

Updates the WHAT_NEW doc with the new changes planned to be released in the `0.50.0` release

docs: updated whats new for 0.50.0

---

WHATS_NEW.md

docs(whatsnew): add entry for v0.51.0

---

pkg/cmd/connector/connector_type/list/list.go

Print size for nom human user. Requested by team

fix: connector type list

---

WHATS_NEW.md

docs(whatsnew): add entry for v0.51.1

---

docs/commands/rhoas_kafka_topic_describe.md
pkg/cmd/kafka/topic/describe/describe.go

chore: sync vendoring with main

---

pkg/shared/contextutil/util.go

Closes #1758 
1. `rhoas connector namespace create`
2. `rhoas context status`

fix: context now correctly stores namespace id

---

docs/commands/rhoas_service-account_describe.md
docs/commands/rhoas_service-account_list.md
go.mod
internal/build/build.go
pkg/cmd/connector/create/create.go
pkg/cmd/login/login.go
pkg/cmd/serviceaccount/create/create.go
pkg/cmd/serviceaccount/delete/delete.go
pkg/cmd/serviceaccount/describe/describe.go
pkg/cmd/serviceaccount/list/list.go
pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go
pkg/cmd/serviceaccount/svcaccountcmdutil/svcaccount_util.go
pkg/core/cmdutil/flagutil/completions.go
pkg/core/localize/locales/en/cmd/serviceaccount.en.toml
pkg/shared/cluster/connect.go
pkg/shared/connection/api/api.go
pkg/shared/connection/api/defaultapi/default_client.go
pkg/shared/connection/kcconnection/builder.go
pkg/shared/connection/kcconnection/keycloak_connection.go
vendor/github.com/redhat-developer/app-services-sdk-go/serviceaccountmgmt/apiv1/api_client.go
vendor/github.com/redhat-developer/app-services-sdk-go/serviceaccountmgmt/apiv1/error/error_sdk.go
vendor/modules.txt

Reverts redhat-developer/app-services-cli#1732

Revert "fix: revert service accounts integration"

---

README.md

Added Go, Go report card, Apache license badges to readme file
Closes #1761

Readme Badges added

---

WHATS_NEW.md

docs(whatsnew): add entry for v0.51.4

---

Makefile

Exclude ./vendor from make format

---

docs/commands/rhoas_connector_create.md
pkg/core/localize/locales/en/cmd/connectors.toml

[Connectors] Fix spelling

---

docs/commands/rhoas.md
docs/commands/rhoas_request.md
pkg/core/localize/locales/en/cmd/request.en.toml

docs(request): typo in descriptions

---

go.mod
go.sum
pkg/cmd/registry/artifact/migrate/export.go
vendor/github.com/redhat-developer/app-services-sdk-go/registryinstance/apiv1internal/client/api_admin.go
vendor/modules.txt

Closes #1774 
1. Run the command to export all artifacts in a service-registry
```
rhoas service-registry artifact export --output-file export.zip
```
2. It should create a new zip folder `export.zip` with all artifacts present in the Service Registry instance.

fix(service-registry artifact): provide content type for export

---

docs/commands/rhoas_connector_namespace.md
docs/commands/rhoas_connector_namespace_create.md
pkg/core/localize/locales/en/cmd/connectors.toml

Remove "--eval" flag from examples.

fix(namespace create): remove eval from examples

---

internal/doc/docs_index.go
internal/doc/modular_docs.go

docs: JX-340: Updates title of CLI command ref

---

docs/commands/rhoas_kafka_create.md
pkg/core/localize/locales/en/cmd/kafka.en.toml

docs(kafka): improve flag descriptions

---

pkg/cmd/dedicated/register/registercluster.go

fix: pass no params during the installation of managed kafka addon

---

pkg/cmd/kafka/list/list.go

Closes # 
1. Have an enterprise cluster
2. `rhoas kafka list` you will see the customer cloud info listed

feat: now listing customer cloud in rhoas kafka list

---

pkg/cmd/kafka/create/create.go
pkg/cmd/kafka/create/data.go
pkg/shared/accountmgmtutil/ams.go
pkg/shared/accountmgmtutil/api.go
pkg/shared/remote/DynamicServiceConstants.go

refactor: of create kafka ams checks for enterprise quota

---

docs/commands/rhoas.md
docs/commands/rhoas_dedicated.md
docs/commands/rhoas_dedicated_deregister-cluster.md
docs/commands/rhoas_dedicated_list.md
docs/commands/rhoas_dedicated_register-cluster.md
pkg/core/localize/locales/en/cmd/dedicated.en.toml

docs: update the docs

---

pkg/cmd/dedicated/deregister/deregister.go

refactor: print the httpresponse

---

pkg/cmd/dedicated/listclusters/list.go
pkg/cmd/dedicated/listclusters/list_test.go
pkg/cmd/kafka/create/create.go
pkg/cmd/kafka/create/data.go
pkg/core/localize/locales/en/cmd/dedicated.en.toml
pkg/core/localize/locales/en/cmd/kafka.en.toml
pkg/shared/accountmgmtutil/ams.go
pkg/shared/accountmgmtutil/api.go
pkg/shared/kafkautil/dedicated_utils.go
pkg/shared/remote/DynamicServiceConstants.go
pkg/shared/remote/service-constants.json

Kafka create with dedicated

---

pkg/cmd/context/contextcmdutil/validator_test.go

Add unit test for `contextcmdutil` validator.
1. Run the command make test.
2. Passing of PR checks imply the tests are passing.

test(context): add test for validator

---

pkg/cmd/kafka/create/create.go
pkg/core/localize/locales/en/cmd/dedicated.en.toml
pkg/core/localize/locales/en/cmd/kafka.en.toml

feat: make enterprise flow the primary flow

---

pkg/cmd/kafka/create/create.go

fix: allows for the creation of trial instances

---

pkg/cmd/kafka/create/create.go
pkg/core/localize/locales/en/cmd/kafka.en.toml

feat: now support trial instances for kafka create

---

pkg/core/localize/locales/en/cmd/kafka.en.toml

docs: update the link to purchase rhoasak quota

---

pkg/cmd/kafka/openshift-cluster/register/registercluster.go

fix(gcp): use "custom-4-32768-ext" machine type for gcp

---

pkg/cmd/kafka/create/create.go
pkg/cmd/kafka/openshift-cluster/openshiftclustercmdutil/dedicated_util.go
pkg/core/localize/locales/en/cmd/kafka.en.toml

Remove gcp and cloud region from kafka create
