redhat-developer/app-services-cli

scripts/install.sh
Follow up to #543 
Run `curl -o- https://raw.githubusercontent.com/craicoverflow/app-services-cli/release-script/scripts/install.sh | bash` to verify it works.
=> chore: fix invalid source repo

docs/commands/rhoas_kafka.adoc, pkg/cmd/kafka/kafka.go
=> chore: disable consumergroup commands which are not ready

.goreleaser.yml, README.md
A path was not updated in the GoReleaser file, causing the build version to be "dev" in a 0.21.1.
=> chore: update paths

locales/cmd/cluster/status/active.en.toml
Update link to the operator from the status
=> fix: use direct link to the operator repository in the status

internal/docs/modular_docs.go
Adding "rhoas" to the title of the CLI command ref guide that is generated for modular docs.
=> docs: update title for mod doc cli guide

pkg/connection/keycloak_connection.go
The MAS-SSO token refresh logic was commented out.
This likely happened by a mistake.
=> fix: MAS-SSO token refresh was not enabled

pkg/cmd/kafka/topic/list/list.go, pkg/kafka/topic/util.go
Resolves #488 
The -1 value for retention size and retention period means "Unlimited". This adds "Unlimited" to the table alongside the true value of -1.
Run `rhoas kafka topic list`:
```
❯ rhoas kafka topic list
NAME             PARTITIONS   RETENTION TIME   RETENTION SIZE  
---------------- ------------ ---------------- ---------------- 
strimzi-canary            3   604800000        -1 (Unlimited)  
topic-1                   1   -1 (Unlimited)   -1 (Unlimited)  
topic-2                   1   1000000          -1 (Unlimited)
```
=> feat(topic): Show 'Unlimited' when value is -1

pkg/cmd/serviceaccount/list/list.go
Closes #575 
```
❯ ./rhoas serviceaccount list
ID (26)                                NAME                   CLIENT ID                                        OWNER                   CREATED AT                     
-------------------------------------- ---------------------- ------------------------------------------------ ----------------------- ------------------------------- 
e488c0a5-de2e-414a-99fd-d39366ba7a0c   owner12-inventory     srvc-acct-081e8cac-023c-476f-a027-47b20206c5bd   mmclaugh_kafka_devexp   2021-04-14 15:38:21 +0000 UTC  
eb1f01f3-2c82-49e6-bc7d-0536802f562a   owner-operator-guiy    srvc-acct-0e5c87b2-f748-4833-989a-100d6f10bd0e   cmolloy_kafka_devexp    0001-01-01 00:00:00 +0000 UTC  
e8355e28-b0de-4a5b-848e-9eef05c0fa78   owner-offsec …
```
=> feat(serviceaccount): add owner column to table

pkg/cmd/kafka/consumergroup/list/list.go, pkg/cmd/kafka/list/list.go, pkg/cmd/kafka/topic/list/list.go, pkg/cmd/serviceaccount/list/list.go
Fixes #579
Run `rhoas kafka list`, `rhoas kafka topic list`, `rhoas serviceaccount list` and `rhoas kafka consumergroup list`, passing `-o json` and `-o yml` (requires 2 runs).
When there are no items, the JSON or YAML will be returned.
```shell
$ ./rhoas kafka list -o yaml
kind: KafkaRequestList
page: 1
size: 0
total: 0
items: []
$ ./rhoas kafka topic list -o json
{
"count": 0,
"items": [],
"limit": 0,
"offset": 0
}
```
=> fix: return request output format when list is empty

CONTRIBUTING.md
We no longer have/need this guide
=> chore: remove mocked kafka use that was outdated

mas-mock/_data_/consumer-groups.json, mas-mock/src/handlers/kafka-admin.js, pkg/cmd/kafka/consumergroup/describe/describe.go, pkg/color/color.go, pkg/iostreams/iostreams.go
Fixes #621 
Set up this project on a Windows machine, check out and run this PR from Command Prompt
OR
Check these screenshots.
**Powershell**
**Cmd**
=> fix(iostreams): make coloured output work on Windows

pkg/cmd/cluster/bind/bind.go, pkg/cmd/cluster/connect/connect.go
Resolves
https://github.com/redhat-developer/app-services-cli/issues/627
This fixing problem with CLI crashing when there is no Kafka List returned due to list command returning nil.
We need to add check for nil for the commands.
=> fix: panic when no kafkas in organization

.github/workflows/commit_lint.yml
This PR adds a GitHub Action which checks that the commit message follows convetional commits.
=> Check for conventional commits

docs/commands/rhoas_kafka_topic_create.adoc, docs/commands/rhoas_kafka_topic_update.adoc, pkg/kafka/topic/validators.go, pkg/localize/locales/en/cmd/kafka_topic_common.en.toml, pkg/localize/locales/en/cmd/kafka_topic_create.en.toml, pkg/localize/locales/en/cmd/kafka_topic_update.en.toml
Remove references to replication factor in docs of `kafka topic` commands.
Closes #665
=> docs(kafka topic): remove rferences to replication factor

pkg/cmd/serviceaccount/create/create.go
Invalid argument for the i18n key `serviceAccount.common.log.info.credentialsSaved`
Closes #678 
1. Create a service account after logging in.
```
go run ./cmd/rhoas serviceaccount create
```
2. A successful creation should print the file path where credentials are saved.
```
Credentials saved to <path-to-file>
```
=> fix: fix invalid i18n arg

cmd/rhoas/main.go
If the config directory does not exist already then an error is thrown as it is not recursively created while migrating the config from the old location.
Backup your config directory: `mv ~/.config ~/.config.bk`
Run a `rhoas` command.
Before this change this would happen:
```shell
❯ ./rhoas whoami
Error migrating config file to new location: mkdir /home/ephelan/.config/rhoas: no such file or directorymkdir /home/ephelan/.config/rhoas: no such file or directory
❯ ./rhoas whoami
Error migrating config file to new location: mkdir /home/ephelan/.config/rhoas: no such file or directorymkdir /home/ephelan/.config/rhoas: no such file or directory
❯ cat ~/.config/rhoas/config.json
After:
```shell
❯ ./rhoas whoami
Error: not logged in. Run "rhoas login" to authenticate
```
=> fix(config): create-config-directory-recursive

pkg/cluster/kubernetes_cluster.go
When executing the cmd `cluster connect` it fails with this error
```
panic: message "cluster.kubernetes.info" not found in language "en"
```
this will just fix it
1. Run `rhoas cluster connect`
=> Fix localize id for cluster info

pkg/cmd/kafka/consumergroup/describe/describe.go, pkg/cmd/kafka/consumergroup/list/list.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/describe/describe.go, pkg/cmd/kafka/list/list.go, pkg/cmd/kafka/topic/create/create.go, pkg/cmd/kafka/topic/describe/describe.go, pkg/cmd/kafka/topic/list/list.go, pkg/cmd/kafka/topic/update/update.go, pkg/cmd/serviceaccount/create/create.go, pkg/cmd/serviceaccount/describe/describe.go, pkg/cmd/serviceaccount/list/list.go, pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go, pkg/cmd/status/status.go, pkg/cmdutil/flags/flags.go
Adds completions for flags such as `--output` and `--file-format`.
Closes #682 
1. Press tab after typing in the following command:
```
./rhoas kafka consumergroup describe -o
```
2. It should suggest the valid options for the output flag - `json`, `yaml` and `yml`
=> feat(completion): static completion for suitable flags

pkg/cmd/kafka/delete/delete.go, pkg/localize/locales/en/cmd/kafka_delete.en.toml
Closes #615 
1. Run `go run ./cmd/rhoas kafka delete <instance-name>`
=> fix(kafka delete): show proper message for delete operation

docs/commands/rhoas_cluster_bind.adoc, pkg/cmd/cluster/bind/bind.go, pkg/localize/locales/en/cmd/cluster_bind.en.toml
1. Expose binding name to support multiple bindings
> NOTE: The only flag that we do not expose now is `bindAsFiles` 
This is because we do not have any documentation for environment variables binding and using it will not work without any doc.
=> chore: expose binding name

docs/commands/rhoas_kafka_topic_list.adoc, pkg/cmd/kafka/topic/list/list.go, pkg/kafka/topic/validators.go, pkg/localize/locales/en/cmd/kafka_topic_list.en.toml
Allow user to filter list of kafka topics by passing `--search` flag to `rhoas kafka topic list`
Closes #697 
1. > go run ./cmd/rhoas kafka topic list --search "pic(-1"
2. It should throw the error message `Error: illegal search value "pic(-1"; only letters (Aa-Zz), numbers, "_", "." and "-" are accepted`
3. Run `go run ./cmd/rhoas kafka topic list --search <search input>`
=> feat(kafka topic): add search flag to list subcommand

pkg/auth/login/login.go, pkg/cmd/kafka/consumergroup/list/list.go, pkg/cmd/kafka/create/create.go, pkg/localize/locales/en/cmd/kafka_create.en.toml
- Open interactive mode when `rhoas kafka create` is run with flags but no name.
- Fix faulty error message while filtering consumergroups by topic.
Closes #703, #704
1. Run `rhoas kafka create --provider aws`, it should open the interactive mode.
2. Run `rhoas kafka consumergroup list --topic <topic-name>` where the topic has no associated consumergroup, it should display the message `Kafka instance "<instance name>" has no consumer groups for topic "<topic-name>"`
=> fix(kafka create): run interactive if no name provided and fix typos

pkg/cmd/kafka/consumergroup/list/list.go, pkg/cmd/kafka/create/create.go, pkg/cmdutil/cmdutil.go
Add dynamic flag completion for `--topic` of `rhoas kafka consumergroup list` and `--provider` for `rhoas kafka create`.
Addresses #591 
1. Press tab twice after `rhoas kafka consumergroup list --topic`, it should auto-fill according to topics in the instance.
2. Press tab twice after `rhoas kafka create <instance name> --provider`, it should suggest the available providers.
=> feat(completion): dynamic completion for suitable flags

scripts/install.sh
Fixes a bug where the binary could not be extracted as the tag has a `v` prefix, but the asset does not, and the tag is used to dynamically build the asset name.
Install latest:
```shell
curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/fix-install-script/scripts/install.sh | bash
```
Install with "v" prefix:
```shell
curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/fix-install-script/scripts/install.sh | bash -s v0.24.4
```
Install without prefix:
```shell
curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/fix-install-script/scripts/install.sh | bash -s 0.24.4
```
=> chore: fix install script

pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go, pkg/localize/locales/en/cmd/serviceaccount.en.toml, pkg/serviceaccount/validation/validation.go, pkg/serviceaccount/validation/validation_test.go
Client side validation for service account ID in interactive mode.
Closes #716
1. Run command to reset credentials for service account in interactive mode.
```
go run ./cmd/rhoas serviceaccount reset-credentials
```
2. Input any random string that is not an UUID, e.g `"kafka"`. It should throw the error:
```
Sorry, your reply was invalid: "kafka" is not a valid UUID
```
=> fix(serviceaccount reset-credentials): validate serviceaccount ID in prompt

pkg/kafka/kafkaerr/error.go
This PR removes a blank line in the error message, which looked unusual.
=> fix(error): remove blank line from error message

pkg/cmd/kafka/list/list.go, pkg/cmd/serviceaccount/delete/delete.go, pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go, pkg/kafka/kafka_util.go, pkg/kafka/kafka_util_test.go, pkg/kafka/topic/validators_test.go, pkg/serviceaccount/validation/validation.go, pkg/serviceaccount/validation/validation_test.go
* Add tests for validation methods.
* Use `ValidateUUID` for service account delete operation. (#720)
Closes #717 
1. Run `rhoas serviceaccount delete --id kafka`
It should throw an error: `Error: "kafka" is not a valid UUID`
2. To validate the unit tests, run `make test/unit`
=> test: add tests for validation methods

pkg/cmd/kafka/topic/update/update.go, pkg/connection/keycloak_connection.go
* Check if topic exists before allowing user to prompt values for update.
* Show proper status of Kafka instance while performing topic/consumer group operation.
Closes #712 #726
1. Try updating a topic that doesn't exist:
```
./rhoas kafka topic update <non-existent>
> Error: topic "<non-existent>" does not exist in Kafka instance "test-instance"
```
2. Delete a Kafka instance from UI, try listing all the topics in that Kafka instance.
```
./rhoas kafka topic list
> Error: Kafka instance "<random name>" is being deleted
```
=> fix(kafka admin): validations and show proper error messages

pkg/cmd/login/login.go
Use oauth2.HTTPClient to perform login
As the go-oidc provider can obtain the custom transport layer
from the context
Closes # 
Run login against a custom auth URL:
```shell
./rhoas login --auth-url "https://keycloakexternal.apps.akoserwa.ipt.integrations.rhmw.io/auth/realms/redhat-external" --insecure
```
=> fix: fix not working insecure login

Makefile
Installing mock globally instead of npx
=> chore: always force latest version of the mock

.github/workflows/gobuild.yml
I noticed that the https://github.com/redhat-developer/app-services-cli/runs/2945125536 is failing because #758 bumped the SDK version which contained breaking changes. The pull request `build` workflow only runs when a `*.go` file has changed but it should also run when `go.mod` changes to catch breaking changes.
=> ci(build): run `go build` when `go.mod` file changes

pkg/cmd/kafka/consumergroup/list/list.go
Closes #773 
Run `rhoas kafka consumergroup list` on an instance you do not own. You should get a nice message like this:
```
Error: you are unauthorized to list these topics
```
=> fix(kafka consumergroup list): fix reference to the wrong i18n ID

docs/commands/rhoas_kafka_topic_create.adoc, pkg/cmd/kafka/topic/create/create.go, pkg/kafka/topic/util.go, pkg/localize/locales/en/cmd/kafka_topic_common.en.toml, pkg/localize/locales/en/cmd/kafka_topic_create.en.toml
User should be able to specify `cleanup policy` while creating a Kafka topic.
Closes #769 
1. Create a kafka topic while passing the `--cleanup-policy` flag.
2. Create a Kafka topic in interactive mode, it should prompt options for `cleanup-policy`.
=> feat(kafka topic create): add cleanup policy flag

docs/commands/rhoas_kafka_topic_update.adoc, pkg/cmd/kafka/topic/update/update.go, pkg/kafka/topic/util.go, pkg/localize/locales/en/cmd/kafka_topic_update.en.toml
User should be able to update cleanup policy of a Kafka topic.
Closes #772 
1. Update a Kafka topic while passing the `--cleanup-policy` flag.
2. Update a Kafka topic in interactive mode
=> feat(kafka topic update): add cleanup policy flag

docs/commands/rhoas.adoc
Build was failing due to outdated doc after merging #776 
Closes # 
1. Do x
2. Do y
=> docs(service-registry): missing link in rhoas.adoc

cmd/rhoas/main.go
Creating for discussion rather than merge directly.
Might be to early to remove it, but I counted +5 releases since this was introduced.
=> fix: remove old workaround for migrating config file name

docs/commands/rhoas.adoc, docs/commands/rhoas_config.adoc, docs/commands/rhoas_config_dev-preview.adoc, docs/commands/rhoas_config_devPreview.adoc, docs/commands/rhoas_service-registry.adoc, docs/commands/rhoas_service-registry_create.adoc, docs/commands/rhoas_service-registry_delete.adoc, docs/commands/rhoas_service-registry_describe.adoc, docs/commands/rhoas_service-registry_list.adoc, docs/commands/rhoas_service-registry_use.adoc, pkg/cmd/config/config.go, pkg/cmd/root/root.go, pkg/localize/locales/en/cmd/config.en.toml, pkg/localize/locales/en/cmd/root.en.en.toml, pkg/localize/locales/en/profile.en.toml, pkg/profile/profile.go, pkg/profile/profile_test.go
```
[wtrocki@graphapi app-services-cli (config)]$ rhoas config devPreview true
Developer Preview commands activated. Use help command to view them.
[wtrocki@graphapi app-services-cli (config)]$ rhoas config devPreview trueds
Error: invalid argument "trueds" for "rhoas config devPreview"
[wtrocki@graphapi app-services-cli (config)]$ rhoas config devPreview false 
Developer Preview commands deactivated.
[wtrocki@graphapi app-services-cli (config)]$ 
```
In 0b79620 I have used single command approach and 2 arguments - one which is config key second is value. 
I think that is overly complex and convoluted.
Current approach uses separate command for each key. 
Drawback is for that approach we getting documentation file generated and there is little bit of duplication in docs, but much simpler …
=> Config command support

pkg/cmd/registry/create/create.go, pkg/cmd/registry/describe/describe.go, pkg/cmd/registry/list/list.go
Enable static auto-completion for output flag of service-registry commands.
Closes #804 
1. Press tab after typing in the command `rhoas service-registry list -o`.
2. It should display the valid output formats as options.
=> feat: enable auto completion for output flag in service-registry commands

pkg/cmd/registry/list/list.go
rhoas service-registry list should not return url as it is very long and obfuscates entire table
Pre:
```
ID   NAME   REGISTRY URL                                                                                                           OWNER                  STATUS  
---- ------ ---------------------------------------------------------------------------------------------------------------------- ---------------------- -------- 
3    test   https://service-registry-stage.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/t/3b8ae86d-1478-4aa8-8b7a-a45d43e299d8   wtrocki_kafka_devexp   ready  
```
Post:
```
[wtrocki@graphapi app-services-cli (registry-table)]$ rhoas service-registry list
ID (4)    NAME    OWNER                  STATUS  
--------- ------- ---------------------- -------- 
3 …
```
=> fix!: Remove URL from table view for serviceregistry list command

docs/commands/rhoas_kafka_consumer-group_list.adoc, pkg/cmd/kafka/consumergroup/list/list.go, pkg/cmd/kafka/topic/list/list.go, pkg/localize/locales/en/cmd/kafka_common.en.toml, pkg/localize/locales/en/cmd/kafka_consumergroup_list.en.toml, pkg/localize/locales/en/cmd/kafka_topic_list.en.toml
BREAKING: flag for deprecated field limit has been removed
Closes #766 
1. List consumer groups after specifying value for `--page` and `--size` flag.
```
./rhoas kafka consumer-group list --page 1 --size 20
```
2. Passing `--limit` to `consumer-group list` command should throw error `unknown flag: --limit`
```
./rhoas kafka consumer-group list --limit 100
```
=> feat(consumer-group list): add flags for pagination

docs/commands/rhoas_kafka_topic_update.adoc, go.mod, go.sum, pkg/cmd/kafka/consumergroup/list/list.go, pkg/cmd/kafka/topic/update/update.go, pkg/kafka/topic/validators.go, pkg/kafka/topic/validators_test.go, pkg/localize/locales/en/cmd/kafka_topic_common.en.toml, pkg/localize/locales/en/cmd/kafka_topic_update.en.toml
User should be able to update number of partitions in a topic. The number of partitions can only increase.
Closes #762 
1. Create a Kafka topic and update its partition count using `--partitions` flag.
```
./rhoas kafka topic update rama-topic --partitions 5
```
2. Partitions can only increase, trying to reduce number of partitions should throw error.
3. Validate the interactive update flow. Try providing values smaller and bigger than current partitions count.
=> feat(kafka topic): partitions flag for update

pkg/cmdutil/cmdutil.go
Dynamic completions for `kafka consumer-group describe` and `kafka consumer-group delete` used to fetch all the consumer groups instead of filtering(as it was not present in server).
1. Create some consumer groups using bin scripts.
2. Press tab twice after setting some initial text for `--id` flag of `kafka consumer-group describe` command.
```
./rhoas kafka consumer-group describe --id co
```
=> fix(kafka consumer-group): use group id filter for dynamic completions

pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go
Skip flag validations for interactive mode.
Closes #837 
1. Try to run `reset-credentials` in interactive mode.
```
go run ./cmd/rhoas service-account reset-credentials
``` 
2. It should prompt for values.
=> fix(service-account): reset-credentials prompt

.goreleaser.yml
Closes # 
1. `goreleaser release --skip-publish --skip-validate --rm-dist`
2. `rpm -qlp ./dist/rhoas_0.26.0-alpha5_linux_amd64.rpm`
3. It should list the `/usr/bin/rhoas` and not `/usr/rhoas`
=> chore: fix binary install path for rpm and deb

pkg/localize/goi18n/go_i18n.go
I did some investigation and believe that there are no issues in any libraries we are using and this could be resolved by changing the root directory of the locales.
go-i18n loads files from the root "locales" directory. The same root should be used when walking the file tree.
Closes #828 
On a Windows machine do the following:
1. Run `rhoas`
2. If successful, the CLI will print the help text to the console.
=> fix(i18n): set "locales" as root dir

pkg/cmd/kafka/consumergroup/describe/describe.go, pkg/color/color.go, pkg/kafka/consumergroup/util.go, pkg/localize/locales/en/cmd/kafka_consumergroup_describe.en.toml
User should be able to see the number of unconsumed partitions in a consumer group using the `rhoas kafka consumer-group describe` command.
Closes #778 
1. Start the mock server by running `make mock-api/start`.
2. Login
```
./rhoas login --api-gateway=http://localhost:8000
```
3. Create a kafka instance
```
./rhoas kafka create <name-of-instance>
```
4. Select the kafka instance running the command `./rhoas kafka use --id <id-of-instance>`.
```
./rhoas kafka use --id <id-of-instance>
```
5. View the consumer group with id `consumer_group_1`.
```
./rhoas kafka consumer-group describe --id consumer_group_1
```
=> feat(consumer-group describe): show unconsumed partitions

go.mod, go.sum, pkg/api/api.go, pkg/cmd/kafka/consumergroup/delete/delete.go, pkg/cmd/kafka/consumergroup/describe/describe.go, pkg/cmd/kafka/consumergroup/list/list.go, pkg/cmd/kafka/topic/create/create.go, pkg/cmd/kafka/topic/delete/delete.go, pkg/cmd/kafka/topic/describe/describe.go, pkg/cmd/kafka/topic/list/list.go, pkg/cmd/kafka/topic/update/update.go, pkg/cmdutil/cmdutil.go, pkg/connection/keycloak_connection.go, pkg/kafka/topic/validators.go
New API splits for topics/groups/acls.
I did not add ACL API yet but have concerns how to do update CLI.
We can either do this:
Or this:
Opinions? FIrst approach is implemented in PR
=> fix: update version of the kafka admin SDK

.github/labeler.yml, .github/workflows/issue-labeler.yml
This PR uses https://github.com/marketplace/actions/regex-issue-labeler to add a "needs-triage" label to all new issues.
=> chore: auto-add "needs-triage" label to new issues

.github/workflows/release.yml
This adds a GitHub Action which will dispatch an event to https://github.com/redhat-developer/app-services-guides whenever there is a new stable release of the CLI.
Relates to #826 - once the event is successful we can add an event receiver on the other side to inject the RHOAS version into the latest guides in a PR.
=> chore: auto-notify guides repo of a new release

pkg/cmd/kafka/consumergroup/list/list.go, pkg/cmd/kafka/topic/create/create.go, pkg/cmd/kafka/topic/delete/delete.go, pkg/cmd/kafka/topic/update/update.go, pkg/localize/goi18n/go_i18n.go, pkg/localize/localize.go
This PR adds a new method to the `Localizer` interface, which returns an error instead of a string. This is useful and can reduce boilerplate by handling error creation directly.
=> refactor: add a method which returns an error

pkg/auth/login/login.go, pkg/auth/login/mas_sso_redirect_handler.go, pkg/cmd/login/login.go, pkg/localize/locales/en/cmd/login.en.toml
Closes https://github.com/redhat-developer/app-services-cli/issues/886
1. Log in to MAS-SSO staging: `rhoas login --mas-auth-url=stg`
2. Note the success message on the redirect URL and terminal output. They should both reflect that MAS-SSO URL.
```shell
❯ ./rhoas login --mas-auth-url stg
Logging in...
Logged in successfully
Logging in to identity.api.stage.openshift.com...
Logged in successfully to identity.api.stage.openshift.com
```
=> fix(login): use mas-sso host in login success message

pkg/cmd/kafka/consumergroup/describe/describe.go, pkg/cmd/kafka/consumergroup/list/list.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/describe/describe.go, pkg/cmd/kafka/list/list.go, pkg/cmd/kafka/topic/create/create.go, pkg/cmd/kafka/topic/describe/describe.go, pkg/cmd/kafka/topic/list/list.go, pkg/cmd/kafka/topic/update/update.go, pkg/cmd/registry/create/create.go, pkg/cmd/registry/describe/describe.go, pkg/cmd/registry/list/list.go, pkg/cmd/serviceaccount/describe/describe.go, pkg/cmd/serviceaccount/list/list.go, pkg/cmd/status/status.go, pkg/cmdutil/flags/flags.go, pkg/dump/dump.go, pkg/localize/goi18n/go_i18n.go, pkg/serviceaccount/credentials/credentials.go
This PR adds a constant for each of the output formats (json, yaml, yml). Everything should remain the same functionally.
Run `rhoas kafka describe --output (json|yaml|yml)` and it should print the format that is expected.
=> refactor(dump): create constants for output formats

pkg/localize/locales/en/cmd/serviceaccount.en.toml
The service-account description validation error message ended with a period which added an extra dot to message printed by terminal.
Closes # 
1. Do x
2. Do y
=> fix(service-account): remove period from description validation error

.vscode/launch.json, pkg/api/api.go, pkg/cmd/registry/artifact/artifacts.go, pkg/cmd/registry/artifact/crud/create/create.go, pkg/cmd/registry/artifact/crud/crud.go, pkg/cmd/registry/artifact/crud/delete/delete.go, pkg/cmd/registry/artifact/crud/get/get.go, pkg/cmd/registry/artifact/crud/list/list.go, pkg/cmd/registry/artifact/crud/update/update.go, pkg/cmd/registry/artifact/download/download.go, pkg/cmd/registry/artifact/metadata/metadata.go, pkg/cmd/registry/artifact/util/constants.go, pkg/cmd/registry/artifact/util/files.go, pkg/cmd/registry/artifact/versions/versions.go, pkg/cmd/registry/create/create.go, pkg/cmd/registry/describe/describe.go, pkg/cmd/registry/registry.go, pkg/connection/keycloak_connection.go, pkg/dump/dump.go, pkg/serviceregistry/registry_util.go, pkg/serviceregistry/registryinstanceerror/error.go
Set of commands to interact with service registry dataplane:
```
Available Commands:
create      Creates new artifact from file or standard input
delete      Deletes all of the artifacts that exist in a given group
download    Download artifacts from registry by using global identifiers
get         Get artifact by id and group
list        List artifacts
metadata    Get artifact metadata
update      Update artifact
versions    Get latest artifact versions by id and group
```
rhoas service-registry artifact create --artifact=my-artifact --group=my-group artifact.json
rhoas service-registry artifact get --artifact=my-artifact --group=my-group file.json 
rhoas service-registry artifact delete --artifact=my-artifact
rhoas service-registry artifact metadata --artifact=my-artifact …
=> Apicurio CLI 

Makefile, docs/commands/rhoas_kafka_list.adoc, internal/build/build.go, pkg/cmd/kafka/consumergroup/list/list.go, pkg/cmd/kafka/list/list.go, pkg/cmd/kafka/topic/list/list.go, pkg/cmd/registry/list/list.go, pkg/cmdutil/cmdutil.go, pkg/cmdutil/constants.go
Default values for `Page` and `Size` should be provided as build variables.
Closes #831 
1. Create a binary of CLI by running the following command (pass 20 as default page size):
```
go build  -ldflags "-X github.com/redhat-developer/app-services-cli/internal/build.DefaultPageNumber="1" -X github.com/redhat-developer/app-services-cli/internal/build.DefaultPageSize="20" -X github.com/redhat-developer/app-services-cli/internal/build.TermsReviewSiteCode="ocm" -X github.com/redhat-developer/app-services-cli/internal/build.TermsReviewEventCode="onlineService" -X github.com/redhat-developer/app-services-cli/internal/build.RepositoryName="app-services-cli" -X github.com/redhat-developer/app-services-cli/internal/build.RepositoryOwner="redhat-developer" -X …
```
=> refactor(pagination): use build variables for default pagination values

pkg/cmd/cluster/bind/bind.go, pkg/cmd/cluster/connect/connect.go, pkg/cmd/cluster/status/status.go, pkg/cmd/kafka/list/list.go, pkg/cmd/kafka/topic/list/list.go, pkg/cmd/registry/artifact/crud/create/create.go, pkg/cmd/registry/artifact/crud/delete/delete.go, pkg/cmd/registry/artifact/crud/get/get.go, pkg/cmd/registry/artifact/crud/list/list.go, pkg/cmd/registry/artifact/crud/update/update.go, pkg/cmd/registry/artifact/download/download.go, pkg/cmd/registry/artifact/metadata/metadata.go, pkg/cmd/registry/artifact/versions/versions.go
Removed unnecessary use of IntVarP(), StringVarP(), BoolVarP() that didn't use or require shorthand parameters and replaced them with IntVar(), StringVar(), and BoolVar().
Closes #897
=> (refactor): Remove Unnecessary Use of VarP()

docs/commands/rhoas_kafka.adoc, docs/commands/rhoas_kafka_consumer-group.adoc, docs/commands/rhoas_kafka_topic.adoc, pkg/cmd/registry/artifact/artifacts.go, pkg/cmd/registry/artifact/crud/create/create.go, pkg/cmd/registry/artifact/crud/delete/delete.go, pkg/localize/locales/en/cmd/kafka.en.toml, pkg/localize/locales/en/cmd/kafka_consumergroup.en.toml, pkg/localize/locales/en/cmd/registry_crud.en.toml, pkg/localize/locales/en/cmd/topic.en.toml
Number of  independent developers provided us feedback that documentation missing clarification what commands are used with instance and what are used for management. I have done this by adding documentation to top level cli objects.
Issue #901
=> docs: update documentation to clarify instance and management commands

pkg/cmd/kafka/consumergroup/describe/describe.go, pkg/kafka/consumergroup/util.go, pkg/localize/locales/en/cmd/kafka_consumergroup_describe.en.toml
Change unconsumed partition to unassigned partition.
1. Run `consumer-group describe` for a consumer group with inactive member(s).
```
./rhoas kafka consumer-group describe --id my-group
```
=> refactor(consumer-group): rename unconsumed to unassigned

pkg/cmd/status/status.go, pkg/status/status.go
`rhoas status` should display the status of registry command if selected.
Closes #902
1. Select a service registry using the `service-registry` use command.
```
./rhoas service-registry use --id 195
```
2. Run the `rhoas status` command, you should be able to see the status of registry along with kafka instance.
3. To see the status of registry specifically, run `./rhoas status registry`
=> feat: display registry status in status cmd

pkg/profile/profile.go
rhoas service-registry and subcommands will now print different label (alpha)
=> chore: change beta to alpha label for commands

pkg/cmd/registry/artifact/artifacts.go, pkg/cmd/registry/artifact/crud/create/create.go, pkg/cmd/registry/artifact/crud/delete/delete.go, pkg/cmd/registry/artifact/crud/get/get.go, pkg/cmd/registry/artifact/crud/list/list.go, pkg/cmd/registry/artifact/crud/update/update.go, pkg/cmd/registry/artifact/download/download.go, pkg/cmd/registry/artifact/metadata/metadata.go, pkg/cmd/registry/artifact/versions/versions.go
1. Positionals for artifact id/name were removed 
2. Positional for file input for create command is the only positional we have
3. For file output we use flag as suggested by @craicoverflow 
```
rhoas service-registry artifact create --artifact-id=my-artifact --group=my-group artifact.json
rhoas service-registry artifact get --artifact-id=my-artifact --group=my-group --file-location=artifact.json
rhoas service-registry artifact download --hash=cab4...al9 --file-location=artifact.json
rhoas service-registry artifact delete --artifact-id=my-artifact
rhoas service-registry artifact metadata --artifact-id=my-artifact --group=my-group
rhoas service-registry artifact update --artifact-id=my-artifact artifact-new.json
rhoas service-registry artifact list --group=my-group --limit=10 page=1
rhoas …
```
=> fix!: remove positional arguments for artifact commands

docs/commands/rhoas_kafka_use.adoc, pkg/cmd/kafka/use/use.go, pkg/cmd/registry/use/use.go, pkg/localize/locales/en/cmd/kafka_use.en.toml, pkg/localize/locales/en/cmd/registry_crud.en.toml
Context and discussion #927 
rhoas kafka use (will print help)
rhoas kafka use --name=yourkafka
rhoas kafka use --id=id
=>  fix!: replace positional use with explicity --name flag

docs/commands/rhoas_kafka_create.adoc, go.mod, go.sum, pkg/cmd/kafka/create/create.go, pkg/cmdutil/constants.go, pkg/iostreams/iostreams.go, pkg/localize/locales/en/cmd/kafka_create.en.toml, pkg/service/status/status.go
Closes https://github.com/redhat-developer/app-services-cli/issues/604
1. Run `rhoas kafka create my-kafka -w`
2. The terminal will output the current status of the Kafka instance. Once it is complete it will print out the Kafka configuration object.
=> feat(kafka): add --wait flag to perform synchronous Kafka creation

pkg/auth/login/mas_sso_redirect_handler.go, pkg/auth/token/token.go, pkg/cmd/whoami/whoami.go
The "preferred_username" claim will be changed to "username" in the near future. This change ensures that both are checked.
1. Run `rhoas whoami`. It will continue to print your username.
2. Now log in using a token. Run `rhoas whoami` and you will see the same result.
=> refactor: check for username and preferred_username claims

pkg/cluster/kubernetes_cluster.go
When working with bind I noticed that we do not print status anymore. 
Quick fix.
Verified already
=> chore: add print to cluster command

pkg/cluster/kcManager.go, pkg/localize/locales/en/cluster_kubernetes.en.toml
We no longer need to print CR as bind command provides this feature
=> fix: remove invalid CR from the connect command

pkg/cmd/kafka/topic/create/create.go
The `topic create` command should be checking if the topic name is "" when in a non-TTY session.
Create a topic in a detached terminal session:
```shell
true | (setsid ./rhoas kafka topic create --name topic2) 2>&1
```
=> fix(topic): condition should check if topic name is empty

pkg/cmd/kafka/delete/delete.go, pkg/localize/locales/en/cmd/kafka_delete.en.toml
Before
```
rhoas kafka delete
? Confirm the name of the instance you want to delete: wtrocki
```
After
```
rhoas kafka delete
? Confirm the name of the instance you want to delete (wtrocki) wtrocki
```
=> fix: add name to confirmation dialog on delete

pkg/cmd/registry/artifact/artifacts.go, pkg/cmd/registry/artifact/crud/create/create.go, pkg/cmd/registry/artifact/crud/update/update.go, pkg/cmd/registry/artifact/metadata/get.go, pkg/cmd/registry/artifact/metadata/set.go, pkg/editor/editor.go, pkg/editor/linux.go, pkg/editor/windows.go
Added new command to edit metadata.
Bonus point - added small utility to open editor in interactive mode (same as in kubernetes)
Interactive mode - opens your system editor and lets you edit values
```
rhoas service-registry artifact metadata-set --artifact-id=test 
```
Explicit mode:
```
rhoas service-registry artifact metadata-set --artifact-id=test --name=test --description=test
```
Verify if changes were applied
```
rhoas service-registry artifact metadata-get --artifact-id=test
```
=> metadata commands

pkg/cmd/registry/delete/delete.go, pkg/cmd/registry/describe/describe.go, pkg/localize/locales/en/cmd/registry_crud.en.toml
Fixed invalid keys assigned as common key.
Verification:
```
rhoas service-registry delete -h 
rhoas service-registry describe -h 
```
=> fix: invalid i18n strings

pkg/kafka/topic/validators.go
The topic name validator should only be returning an error
when this topic name already exists.
Closes #1003 
1. Run `rhoas kafka create`
2. Enter a name in the interactive prompt.
3. It should proceed past this stage.
=> fix(topic): only return error on http.StatusOK

pkg/kafka/kafka_util.go
I've been testing rhoas CLI and found the following NPR. Here is the fix.
❯ ./rhoas kafka create
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x248874d]
goroutine 1 [running]:
github.com/redhat-developer/app-services-cli/pkg/kafka.(*Validator).ValidateNameIsAvailable(0xc0008d0168, 0x2616a40, 0xc0003bb560, 0x0, 0x0)
/Users/allyse/Dev/app-services-cli/pkg/kafka/kafka_util.go:109 +0x12d
github.com/AlecAivazis/survey/v2.Ask(0xc00072b3d0, 0x1, 0x1, 0x25bd7c0, 0xc0006a0100, 0xc0001e9408, 0x2, 0x2, 0x0, 0x0)
/Users/allyse/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.1/survey.go:329 +0x402
github.com/AlecAivazis/survey/v2.AskOne(...)
/Users/allyse/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.1/surv …
=> fix: fixed NPR when validating Kafka name

cmd/rhoas/main.go, pkg/cmd/registry/artifact/metadata/set.go, pkg/connection/builder.go, pkg/connection/keycloak_connection.go, pkg/serviceregistry/api.go
Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation
https://github.com/golang/go/wiki/CodeReviewComments#error-strings
=> style: error strings should not be capitalized

pkg/status/status.go
Variable 'len' collides with the builtin function
=> refactor: variable 'len' collides with the builtin function

pkg/iostreams/iostreams.go
Variable 'io' collides with imported package name
=> chore: variable 'io' collides with imported package name

pkg/connection/keycloak_connection.go
Variable 'api' collides with imported package name
=> chore: variable 'api' collides with imported package name

pkg/cmd/logout/logout_test.go
Variable 'factory' collides with imported package name
=> chore: variable 'factory' collides with imported package name

pkg/cmd/registry/artifact/metadata/set.go
Variable 'editor' collides with imported package name
=> chore: variable 'editor' collides with imported package name

pkg/cmd/registry/artifact/artifacts.go, pkg/cmd/registry/artifact/crud/create/create.go, pkg/cmd/registry/artifact/crud/delete/delete.go, pkg/cmd/registry/artifact/crud/get/get.go, pkg/cmd/registry/artifact/crud/list/list.go, pkg/cmd/registry/artifact/crud/update/update.go, pkg/cmd/registry/artifact/download/download.go, pkg/cmd/registry/artifact/metadata/get.go, pkg/cmd/registry/artifact/metadata/set.go, pkg/cmd/registry/artifact/util/constants.go, pkg/cmd/registry/artifact/versions/versions.go, pkg/localize/locales/en/cmd/artifact.en.toml, pkg/localize/locales/en/cmd/registry_crud.en.toml
=> chore: i18n support for service registry art Artifact commands

docs/commands/rhoas_kafka_consumer-group.adoc, docs/commands/rhoas_kafka_consumer-group_reset-offset.adoc, pkg/cmd/flag/validation.go, pkg/cmd/kafka/consumergroup/consumergroup.go, pkg/cmd/kafka/consumergroup/delete/delete.go, pkg/cmd/kafka/consumergroup/resetoffset/reset_offset.go, pkg/cmdutil/flags/flags.go, pkg/kafka/consumergroup/util.go, pkg/kafka/consumergroup/validators.go, pkg/kafka/consumergroup/validators_test.go, pkg/localize/locales/en/cmd/kafka_consumergroup_reset_offset.toml, pkg/localize/locales/en/cmd/serviceaccount_reset_credentials.en.toml
Implement `rhoas kafka consumer-group reset-offset` command.
Closes #763 
1. Start mock server.
```
make mock-api/start
```
2. Select a Kafka instance using
```
rhoas kafka use --id <id-of-instance>
```
3. Run the following command to reset offset for a consumer group:
```
go run ./cmd/rhoas kafka consumer-group reset-offset --id my-app --offset earliest --topic topic-1
```
4. The output should be updated consumers in a tabular form
1. Create a Kafka instance,a Kafka topic and Kafka consumer group.
2. After consuming a few messages, disconnect the consumer group.
3. Run the following command to reset offset for a consumer group:
```
./rhoas kafka consumer-group reset-offset --id my-group --offset earliest -v
```
4. Run the following command to reset offset for specific consumers in a …
=> feat(consumer-group): add reset-offset command

.github/CODEOWNERS
Added a CODEOWNERS file to assign reviewers automatically. 
We can customize this if needed, but I don't think we should assign individuals to specific areas.
=> chore(github): add a CODEOWNERS file

pkg/auth/login/login.go, pkg/cmd/login/login.go
Log in, and you will not see the messages related to MAS-SSO unless you pass the `-v` flag.
```shell
$ rhoas login
Logging in...
Logged in successfully
```
=> fix: remove double-login messages

cmd/rhoas/main.go, pkg/auth/login/login.go, pkg/cluster/kcManager.go, pkg/cluster/kubernetes_cluster.go, pkg/cluster/serviceBinding.go, pkg/cmd/kafka/consumergroup/resetoffset/reset_offset.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/delete/delete.go, pkg/cmd/kafka/use/use.go, pkg/cmd/login/login.go, pkg/cmd/logout/logout.go, pkg/cmd/registry/artifact/crud/get/get.go, pkg/cmd/registry/artifact/download/download.go, pkg/cmd/registry/artifact/metadata/get.go, pkg/cmd/registry/artifact/metadata/set.go, pkg/cmd/registry/artifact/versions/versions.go, pkg/cmd/registry/create/create.go, pkg/cmd/registry/delete/delete.go, pkg/cmd/registry/use/use.go, pkg/cmd/serviceaccount/create/create.go, pkg/cmd/serviceaccount/delete/delete.go, pkg/icon/icon.go, pkg/localize/locales/en/cmd/kafka.en.toml
Follow up to the great work done in #1046 
Three things are covered here:
- Renamed methods
- Removed the extra space between the Error prefix and message
- Detect if an emoji is used, and if so it capitalizes the first character if the message.
Windows:
```shell
$ rhoas kafka topic list
Error: not logged in to identity.api.openshift.com. 
```
Linux:
```shell
$ rhoas kafka topic list
❌ Not logged in to identity.api.openshift.com.
```
=> fix: remove space after prefix from root error

cmd/rhoas/main.go, pkg/cmd/factory/default.go, pkg/cmd/root/root.go, pkg/logging/logger.go, pkg/logging/std_logger.go
I've added a new SetDebug() function to the Logger interface and implemented it in the StdLoggerBuilder. Also, I've moved debug.Enabled() out of default.go file to the main.go and placed it after the command line arguments definition, so the verbose flag will be properly read and set.
Closes #1034
=> fix: fixed the problem with a verbose flag

docs/commands/rhoas_cluster_bind.adoc, go.mod, go.sum, pkg/cluster/serviceBinding.go, pkg/cmd/cluster/bind/bind.go, pkg/cmd/root/root.go, pkg/localize/locales/en/cmd/cluster_bind.en.toml
We are adding deploymentConfig support by extra flag.
Why flag instead of showing both?
Deployment config is typically problematic with binding (extra rollouts are needed and we cannot make sure that binding will be valid). We needed to provide extra documentation etc. to support that - adding it by default will cause confusion and problems. 
It will also break our existing guides :/
This change doesn't introduce any multiservice aritecture. 
This is going to be done in separate feature branch done by @rkpattnaik780 
I have prepared layer for that refactoring but we need to work on top of the changes that Rama has right now.
```
[wtrocki@graphapi app-services-cli (support-bind ✗)]$ rhoas cluster bind --deployment-config 
? Select Kafka instance to connect: pete
Namespace not provided. …
```
=> Service binding supporting deployment config

pkg/cmd/registry/artifact/crud/list/list.go
Closes #911 
**Verification Steps**
Type of change
=> refactor: use make to create fixed size list

docs/commands/rhoas_kafka.adoc, docs/commands/rhoas_kafka_update.adoc, pkg/auth/token/token.go, pkg/cmd/kafka/kafka.go, pkg/cmd/kafka/update/update.go, pkg/localize/locales/en/cmd/kafka_update.en.toml
The `rhoas kafka update` command was hidden as there needed to be some changes in the backend. This has been enabled now, so we can make this command available to users.
1. Log in as an org admin.
1. Ensure `RHOAS_DEV=false` or unset.
1. Run `rhoas kafka update`
2. You will be shown a list of users to choose from.
3. Log in as a non-admin.
4. Run `rhoas kafka update`, you should see:
```shell
$ rhoas kafka update
Only organization administrators have the ability to update a Kafka instance.
```
=> feat: enable kafka update command

pkg/auth/login/login.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/update/update.go, pkg/cmd/login/login.go, pkg/iostreams/iostreams.go, pkg/ioutil/spinner/spinner.go
Closes #1094 
This pull request primarily adds a visual spinner to the login command. I've also added a custom `spinner` package which abstracts the `github.com/briandowns/spinner` and allows you to pass the localized ID directly and it will localize the message.
Run `rhoas login` and watch the command prompt during each phase as it starts a spinner and will stop it after you have logged in.
=> refactor(login): add visual spinner to login command

pkg/localize/locales/en/cmd/artifact.en.toml
Removing redundant messages - most of the users will not specify a group when working with the registry. 
Keeping the message for informative reasons.
=> fix: group message update

pkg/cmd/registry/artifact/state/state.go
[wtrocki@graphapi app-services-cli (state-fix ✗)]$ rhoas service-registry artifact state-set --artifact-id=test
Using default artifacts group.
❌ Invalid value '' for ArtifactState: valid values are [ENABLED DISABLED DEPRECATED]. Run the command in verbose mode using the -v flag to see more information
=> fix: add proper validation for state

docs/commands/rhoas_kafka_consumer-group_reset-offset.adoc, docs/commands/rhoas_kafka_topic_update.adoc, docs/commands/rhoas_kafka_update.adoc, docs/commands/rhoas_service-registry_artifact_update.adoc, pkg/cmd/kafka/consumergroup/resetoffset/reset_offset.go, pkg/cmd/kafka/topic/update/update.go, pkg/cmd/kafka/update/update.go, pkg/cmd/registry/artifact/crud/update/update.go, pkg/localize/locales/en/cmd/kafka.en.toml, pkg/localize/locales/en/cmd/kafka_consumergroup_reset_offset.toml, pkg/localize/locales/en/cmd/kafka_update.en.toml
Closes #1092 
1. Run `rhoas kafka update`, `rhoas kafka topic update`, `rhoas kafka consumer-group reset-offset`. All will no longer show any JSON output.
=> fix!: remove --output flag from update commands

Makefile, cmd/rhoas/main.go, go.sum, pkg/cmd/docs/docs.go, pkg/cmd/root/root.go
closes #1098 
this remains hidden from documentation and completions.
1. Run `rhoas docs -d ./docs/commands -f adoc` to generate documentation into the same folder as the old format.
=> feat: add hidden docs command

.goreleaser.yml
Closes #940 
This installs a LICENSE file with the RPM distribution type:
```shell
$ ls /usr/share/licenses/rhoas
LICENSE
```
=> chore: install license with RPM

docs/commands/rhoas_kafka.adoc, docs/commands/rhoas_kafka_acl.adoc, docs/commands/rhoas_kafka_acl_list.adoc, docs/commands/rhoas_kafka_consumer-group_reset-offset.adoc, pkg/cmd/kafka/acl/acl.go, pkg/cmd/kafka/acl/list/list.go, pkg/cmd/kafka/kafka.go, pkg/localize/locales/en/cmd/acl.en.toml
This PR adds `rhoas kafka acl list` command to list all the Kafka ACL rules for a given instance.
Closes #1172
1. `rhoas kafka -h` should display `acl` in list of sub commands
2. `rhoas kafka acl list` should display ACL rules for the selected Kafka instance.
=> feat(kafka acl): add base and list command

docs/commands/rhoas_kafka_consumer-group_reset-offset.adoc, pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go
=> fix: add token endpoint URL to credentials file

.cases/termsandconditions.sh, Makefile, internal/build/build.go, pkg/ams/TermsAndConditionsSpec.go, pkg/ams/ams.go, pkg/ams/terms.go, pkg/cmd/kafka/create/create.go, pkg/cmd/registry/create/create.go
Requires extra work and untested but code should be ok to review.
Fixes https://github.com/redhat-developer/app-services-cli/issues/1275
=> Use remote spec for terms and conditions

.vscode/launch.json, pkg/kafka/aclutil/enums.go, pkg/kafka/aclutil/util.go
The Admin API will soon introduce a breaking change where the values from /resource-operations will change to match the enums from the aPI. This is a compatibility fix to ensure both scenarios are supported and can be removed in the future.
Backend change: https://github.com/bf2fc6cc711aee1a0c2a/kafka-admin-api/pull/140
1. In the delete command, modify `resourceOperations`:
```go
resourceOperations["TOPIC"] = []string{
"ALL",
}
delete(resourceOperations, "topic")
```
2. Then, delete the corresponding ACL:
```shell
./rhoas kafka acl delete --operation all --permission allow --topic "*" --all-accounts
```
=> refactor: support different resource types and operations

docs/commands/rhoas_kafka_acl.adoc, docs/commands/rhoas_kafka_acl_list.adoc, pkg/kafka/aclutil/acl_table.go, pkg/kafka/aclutil/enums.go, pkg/localize/locales/en/cmd/acl.en.toml
Closes #1247 
Run `rhoas kafka acl list`:
```shell
$ rhoas kafka acl list
PRINCIPAL (5)                                    PERMISSION   OPERATION   DESCRIPTION                    
------------------------------------------------ ------------ ----------- ------------------------------- 
All accounts                                     allow        describe    group is "*"                   
All accounts                                     allow        describe    cluster is "*"                 
All accounts                                     allow        describe    topic is "*"                   
srvc-acct-17601ff7-89f8-48c6-af99-e3e925cc433c   allow        all         topic starts with "RedHat"     
srvc-acct-17601ff7-89f8-48c6-af99-e3e925cc433c   allow        all         topic starts …
```
=> fix: use mapped lowercase values in ACL table

pkg/cmd/kafka/create/create.go, pkg/cmd/registry/create/create.go, pkg/cmdutil/flagutil/flagset.go
Closes #1294 
Run `rhoas kafka create --bypass-terms-check` in debug mode. You should see that the terms check is never executed by there being no `Checking if terms and conditions have been accepted` debug message.
=> chore: add hidden flag to skip terms check

.goreleaser.yml, Makefile, cmd/rhoas/main.go, internal/build/build.go, pkg/cmd/login/login.go, pkg/cmd/version/version.go
This is a stop-gap solution to #1290 by ensuring that version checking and printiing will only occur for the upstream CLI, when the `BuildSource` build variable is "github".
=> refactor: check for new version in upstream build only

pkg/auth/login/mas_sso_redirect_handler.go, pkg/auth/login/static/mas-sso-redirect-page.html
Closes #1304 
Run `rhoas login`. The second redirect page will auto-close so that you do not see it.
=> fix: auto-close MAS-SSO redirect page

pkg/cmd/kafka/update/update.go, pkg/localize/locales/en/cmd/acl.en.toml
Closes #1302, #1224
1. Run `rhoas kafka update --owner foo_user`
2. This should display the existing user and the new user to be set
=> fix(kafka update): broken preview

docs/commands/rhoas_service-registry_artifact_create.adoc, pkg/cmd/registry/artifact/crud/create/create.go, pkg/localize/locales/en/cmd/artifact.en.toml
Print URL to UI of the artifact created.
Closes #1321 
1. Create an artifact:
```
./rhoas service-registry artifact create  --file ./artifact.json --name rama-tes35  --type JSON --group schema --artifact-id rama-53909uj
```
It should display the web url for the artifact.
=> feat(service-registry artifact create): print url to UI

pkg/cmd/registry/artifact/crud/create/create.go, pkg/cmd/registry/artifact/metadata/get.go, pkg/cmd/registry/artifact/util/util.go
`rhoas service-registry artifact metadata-get` should print URL to UI along with the fetched metadata.
Closes #1323
1. Run the command to fetch metadata of an artifact.
```
./rhoas service-registry artifact metadata-get --artifact-id <id>
```
The URL to artifact should be printed.
=> feat(artifact metadata-get): print url to UI

docs/commands/rhoas_cluster_connect.adoc, pkg/cluster/connect.go, pkg/cluster/services/custom_connection.go, pkg/cluster/services/kafka.go, pkg/cluster/services/service-registry.go, pkg/localize/locales/en/cmd/cluster.en.toml
Display commands required to grant access to the service-account.
1. Connect a service registry instance with the cluster:
```
rhoas cluster connect --service-type service-registry --namespace default -y
```
It should print command to give access to the the service registry
=> fix(cluster connect): print access commands separately for services

.github/workflows/gobuild.yml, .github/workflows/modular-docs-publish.yml, CONTRIBUTING.md, Makefile
This trick found [in this article](http://marmelab.com/blog/2016/02/29/auto-documented-makefile.html) introspects the Makefile to dynamically create an output for `make help`. 
I've changed some commands to not include a `/` as it did not work for these.
Run `make help`
=> chore: add a self-maintaining help command to Makefile

pkg/cmd/kafka/acl/admin/admin.go, pkg/cmd/kafka/acl/create/create.go, pkg/cmd/kafka/acl/delete/delete.go, pkg/cmd/kafka/acl/grant/grant.go, pkg/cmd/kafka/acl/list/list.go, pkg/kafka/aclutil/constants.go, pkg/kafka/aclutil/util.go, pkg/localize/locales/en/cmd/acl.en.toml
Kafka acl commands should restrict user from setting principal value to `all` along with `*`.
Closes #1330 
1. Try to run grant-access with user set to all
> rhoas kafka acl grant-access --producer --user all --topic x 
It should throw the error: `to set a wilcard on the ACL principal, pass "--all-accounts".`
=> fix(kafka acl): disallow all alias for principal

cmd/rhoas/main.go, pkg/cmd/kafka/acl/create/create.go, pkg/cmd/kafka/acl/delete/delete.go, pkg/cmd/kafka/acl/grant/grant.go, pkg/icon/icon.go, pkg/kafka/aclutil/util.go, pkg/localize/locales/en/cmd/acl.en.toml
Iterate through all flag options to show every missing flag instead of the immediately missing flag option.
Closes #1229
Verification needs different flag combinations to be tried out for the commands:
- `rhoas kafka acl create`
- `rhoas kafka acl delete`
- `rhoas kafka acl grant-access`
=> refactor(kafka acl): smarter error handlings

pkg/localize/locales/en/cmd/cluster.en.toml
Based on https://github.com/bf2fc6cc711aee1a0c2a/srs-fleet-manager/issues/168#issuecomment-983023914
Sa for registry will have no permissions by default and it will always require user to execute that command.
=> fix: remove non read only docs for srs

docs/commands/rhoas_kafka_update.adoc, pkg/cmd/kafka/update/update.go, pkg/cmdutil/flagutil/tribool.go, pkg/localize/locales/en/cmd/kafka_update.en.toml
Add `--reauthentication` flag to Kafka update
1. Set value for "enable_reauthentication" using the `--reauthentication` flag
`rhoas kafka update --reauthentication false`
2. Try running kafka update in interactive mode
=> feat(kafka update): add reauthentication flag

pkg/localize/locales/en/common.en.toml, pkg/telemetry/telemetry.go
Telemetry was disabled this change removes temporary 
This change requires release both upstream and downstream
1. Download official build for that PR: https://github.com/redhat-developer/app-services-cli/releases/tag/v0.36.0-dev1
2. Execute any command (you should be asked for telemetry consent)
3. Review usage in the woopra (ping me if you do not have access)
Verify if env var disables and enables telemetry:
1. RHOAS_TELEMETRY=false rhoas status
2. RHOAS_TELEMETRY=true
3. RHOASCONFIG=/tmp/test.json rhoas kafka list
1. wget https://gist.githubusercontent.com/wtrocki/aba66607aba5dcbddf234cafcd0aa4e1/raw/249425b98cad25dfdb354ab6ef7e6a526b8af46d/rhoasStatus.js
2. Execute "node [rhoasStatus.js](https://gist.github.com/wtrocki/aba66607aba5dcbddf234cafcd0aa4e1)"
stdout:
Service Registry …
=> Enable command collections

docs/commands/rhoas_service-registry_create.adoc, pkg/cmd/registry/artifact/crud/create/create.go, pkg/cmd/registry/artifact/metadata/set.go, pkg/cmd/registry/create/create.go, pkg/localize/locales/en/cmd/registry_crud.en.toml
Add `--description` flag to `service-registry create` command.
1. Try creating a service registry instance with description flag.
```
rhoas service-registry create --name test-instance --description "random description"
```
2. Create a registry instance through interactive mode:
```
rhoas service-registry create
```
=> feat(service-registry): add description flag for create command

pkg/cmd/registry/artifact/crud/create/create.go, pkg/cmd/registry/artifact/crud/update/update.go, pkg/cmd/registry/artifact/util/files.go, pkg/cmd/registry/artifact/util/files_test.go, pkg/cmdutil/cmdutil.go, pkg/localize/locales/en/cmd/artifact.en.toml
It should be possible to create/update artifacts using remote URLs.
1. Pass url as value for `--file` while creating an artifact.
```
rhoas service-registry artifact create --type OPENAPI --file "https://raw.githubusercontent.com/bolcom/avro-schema-viewer/master/docs/assets/avsc/1.0/schema.avsc" --artifact-id foo_id
```
2. Pass url as value for `--file` to update an artifact.
```
rhoas service-registry artifact update --artifact-id foo_id --group DEFAULT --file "https://raw.githubusercontent.com/bolcom/avro-schema-viewer/master/docs/assets/avsc/1.0/schema.avsc"
```
=> feat(service-registry artifact): allow loading artifact from remote URL

docs/commands/rhoas_service-registry_artifact_list.adoc, pkg/cmd/registry/artifact/crud/list/list.go, pkg/localize/locales/en/cmd/artifact.en.toml
Added `--name`, `--labels`, `--description` and `--properties` flag to `service-registry artifact list` command to enable filtering the artifacts.
Run the following commands by adjusting the parameters in accordance to the artifact list:
```
rhoas service-registry artifact list --name sample
rhoas service-registry artifact list --label "my-label"
rhoas service-registry artifact list --description sample
```
=> feat(artifact list): add flags to filter result

docs/commands/rhoas_kafka_acl_grant-admin.adoc, pkg/cmd/kafka/acl/admin/admin.go
Add instance id flag to `grant-admin` command. Earlier command used context to set the Kafka instance id. 
1. Run command to grant admin access for a specific Kafka instance
```
rhoas kafka acl grant-admin --user foo_user --instance-id c727fgnstb6seui1vnp0
```
=> feat(acl grant-admin): add flag for instance id

.github/CODEOWNERS
The CODEOWNERS file needs to pair a glob with an owner. It was missing the glob.
=> chore: fix CODEOWNERS not working

pkg/cmd/kafka/acl/admin/admin.go, pkg/cmd/kafka/acl/create/create.go, pkg/cmd/kafka/acl/delete/delete.go, pkg/cmd/kafka/acl/grant/grant.go, pkg/localize/locales/en/cmd/acl.en.toml
The i18n library allows you to pass a number to indicate plurality, so I updated the messages to have a plural and singular form.
Closes #1300 
**Plural grant-access**
```shell
❯ rhoas kafka acl grant-access --producer --consumer --service-account dfgreg --topic enda --group enda
The following ACL rules will be created:
PRINCIPAL (7)    PERMISSION   OPERATION   DESCRIPTION              
---------------- ------------ ----------- ------------------------- 
dfgreg           allow        describe    topic is "enda"          
dfgreg           allow        read        topic is "enda"          
dfgreg           allow        read        group is "enda"          
dfgreg           allow        write       topic is "enda"          
dfgreg           allow        create      topic is "enda" …
```
=> fix: add plural form for ACL messages

go.mod, internal/telemetry/segment.go, internal/telemetry/telemetry.go, pkg/api/apis.go, pkg/core/ioutil/editor/linux.go
Remove any logging from analytics so it is not issuing/obfuscating user response. 
Telemetry delivery can fail with bad network etc. so we should not print that. It is not critical for user to see it as well we cannot do much with error anyway.
=> fix: remove logging from segment

README.md
This trivial PR fixes a wrong path to the RHOAS documentation page about commands from the landing page.
=> Fixed path to the rhoas commands doc page

pkg/core/ioutil/dump/dump.go
YAML output was not being output in color due to a change in the output text of `yq --version`, from which we detect the YQ version.
**Prerequisites**
- yq 4.x
Run `rhoas kafka describe -o yaml` and verify that it has been colored.
=> fix: parse yq version for different outputs

pkg/core/ioutil/spinner/spinner.go
Changed the color of the spinner to cyan to make it stand out more.
I actually wanted to do it in red to align with the product color scheme but it could be mistaken to mean an error.
=> feat: make the spinner cyan color

pkg/cmd/kafka/topic/topiccmdutil/validators.go, pkg/cmd/kafka/topic/topiccmdutil/validators_test.go
```
#fail 
rhoas kafka topic create --partitions=3000
rhoas kafka topic create --partitions=900
```
=> fix: change partition limit for new topic creation

docs/commands/rhoas_cluster_connect.md, docs/commands/rhoas_service-registry_role.md, docs/commands/rhoas_service-registry_role_add.md, pkg/cmd/registry/artifact/role/add/add.go, pkg/cmd/registry/artifact/role/list/list.go, pkg/cmd/registry/artifact/util/constants.go, pkg/cmd/registry/artifact/util/rolemapping.go, pkg/core/localize/locales/en/cmd/cluster.en.toml, pkg/core/localize/locales/en/cmd/role.toml, pkg/core/localize/locales/en/cmd/serviceaccount.en.toml
UI using some different values so we see this as confusing/mixed UX that should be aligned. 
New roles are introduced in breaking fashion as we can easily provide feedback to users about the change
```
rhoas service-registry role add --role Viewer --username wtrocki_kafka_devexp
rhoas service-registry role list
```
=> fix!: align roles for service registry

docs/commands/rhoas_cluster_connect.md, docs/commands/rhoas_service-registry_role.md, docs/commands/rhoas_service-registry_role_add.md, pkg/cmd/registry/artifact/util/constants.go, pkg/core/localize/locales/en/cmd/cluster.en.toml, pkg/core/localize/locales/en/cmd/role.toml, pkg/core/localize/locales/en/cmd/serviceaccount.en.toml
We want the CLI to be a relatively quick way to execute operations against the service. By forcing users to toggle the case of a value, we are actually slowing them down.
As a rule of thumb we should use lowercase in almost all cases except for exceptional circumstances.
=> fix!: use lowercase values for registry roles

pkg/cmd/kafka/consumergroup/groupcmdutil/validators.go, pkg/cmd/serviceaccount/resetcredentials/reset_credentials.go, pkg/core/localize/locales/en/cmd/kafka.en.toml
Wrong error message for validating offset flag of `consumer-group reset-offset`. 
1. Run command to reset offset for a consumer group with random offset value
```
./rhoas kafka consumer-group reset-offset --id vkjkjv --topic naruto --offset ppl 
```
=> fix(consumer-group): offset validation error message

go.mod, go.sum, pkg/cmd/kafka/acl/delete/delete.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/list/list.go, pkg/cmd/serviceaccount/list/list.go, pkg/shared/kafkautil/util.go
When creating kafka should:
- not validate interactive mode - it would be valid by default 
- list only supported types for creation
```
wtrocki@graphapi app-services-cli (interactive-create)]$ rhoas kafka create            
? Name: test
? Cloud Provider: aws
? Cloud Region:  [Use arrows to move, type to filter, ? for more help]
> us-east-1
```
=> Interactive create

docs/commands/rhoas_service-registry_rule.md, docs/commands/rhoas_service-registry_rule_describe.md, docs/commands/rhoas_service-registry_rule_enable.md, docs/commands/rhoas_service-registry_rule_list.md, pkg/cmd/registry/rule/describe/describe.go, pkg/cmd/registry/rule/enable/enable.go, pkg/cmd/registry/rule/list/list.go, pkg/cmd/registry/rule/rule.go, pkg/cmd/registry/rule/rulecmdutil/constants.go, pkg/cmd/registry/rule/rulecmdutil/error.go, pkg/cmd/registry/rule/rulecmdutil/validator.go, pkg/core/localize/locales/en/cmd/rule.en.toml
Add `describe` and `list` command for `service-registry rules`.
```
Fetching global compatibility rule for artifacts in the Service Registry instance
{
"config": "FULL",
"type": "COMPATIBILITY"
}
```
```
Fetching global rules for artifacts in Service Registry Instance
RULE TYPE       DESCRIPTION                                                 STATUS    
--------------- ----------------------------------------------------------- ---------- 
VALIDITY        Ensure that content is valid when updating this artifact.   DISABLED  
COMPATIBILITY   Enforce a compatibility level when updating this            ENABLED   
artifact (for example, Backwards Compatibility).                      
Run describe command to view confiuration of enabled rule
```
1. Run the following commands for list …
=> feat(service-registry rule): add describe and list command

docs/commands/rhoas_kafka_acl_delete.md, pkg/cmd/kafka/acl/aclcmdutil/constants.go, pkg/cmd/kafka/acl/aclcmdutil/util.go, pkg/cmd/kafka/acl/create/create.go, pkg/cmd/kafka/acl/delete/delete.go, pkg/core/cmdutil/flagutil/deprecation.go, pkg/core/localize/locales/en/cmd/acl.en.toml
Creating for early feedback for https://github.com/redhat-developer/app-services-cli/issues/1430
Validation for delete command were redundant preventing users from deleting multiple acls. 
For example it would not be possible to remove all ACLs for Service account.
After this change it is possible:
```
✔️  Deleted 5 ACLs from Kafka instance "wtrocki"
The following ACL rules were deleted:
PRINCIPAL (5)    PERMISSION   OPERATION   DESCRIPTION               
---------------- ------------ ----------- -------------------------- 
test             allow        write       transactional-id is "*"   
test             allow        describe    topic starts with "test"  
test             allow        write       topic starts with "test"  
test             allow        create      topic starts with …
```
=> fix: allow to delete all ACLs for principal

pkg/cmd/kafka/create/create.go, pkg/core/localize/locales/en/cmd/kafka.en.toml
Switching to support all error types that we can get back from the API
=> fix: clarify errors for kafka create

docs/commands/rhoas_service-registry_rule_disable.md, pkg/cmd/registry/rule/describe/describe.go, pkg/cmd/registry/rule/disable/disable.go, pkg/cmd/registry/rule/enable/enable.go, pkg/cmd/registry/rule/list/list.go, pkg/cmd/registry/rule/update/update.go, pkg/core/localize/locales/en/cmd/rule.en.toml
Add confirmation for disable operation and remove spinners
1. Disable rule with and without passing `--y` flag.
2. Run any rule command to check the help texts
=> fix(service-registry rule): confirm prompt ant remove spinners

CONTRIBUTING.md
Add up-to-date instructions in `CONTRIBUTING.md`.
=> docs(contributing): remove outdated instructions

.github/workflows/release.yml
Sends a workflow dispatch event to https://github.com/redhat-developer/app-services-tools to initiate a new image release to Quay.
There is no way to verify this until our next release.
=> ci: notify tools repo when there is a new release

docs/commands/rhoas_kafka_topic_create.md, docs/commands/rhoas_kafka_topic_update.md, pkg/core/localize/locales/en/cmd/kafka.en.toml
The build is currently failing as flag description for topic retention byte ends with a fullstop.
The build GitHub action should pass.
```
--- FAIL: Test_ValidateCommandsUsingCharmilValidator (0.01s)
validator_test.go:56: validationErr was not empty, got length: 2; want 0
validator_test.go:61: PUNCTUATION_RULE: cmd rhoas kafka topic create: full stop in the flag usage
validator_test.go:61: PUNCTUATION_RULE: cmd rhoas kafka topic update: full stop in the flag usage
```
=> fix: build failing at test

docs/commands/rhoas_service-registry_rule_disable.md, pkg/cmd/registry/rule/describe/describe.go, pkg/cmd/registry/rule/disable/disable.go, pkg/cmd/registry/rule/enable/enable.go, pkg/cmd/registry/rule/update/update.go, pkg/core/localize/locales/en/cmd/rule.en.toml
Follow up PR for #1466 
1. Run service-registry rule commands for global rules.
=> docs(service-registry rule): add disable example and fix logs

pkg/cmd/registry/rule/rulecmdutil/mappings.go
See https://github.com/Apicurio/apicurio-tasks/issues/154
Closes https://github.com/Apicurio/apicurio-tasks/issues/154
Configure a global validity rule like this:
`rhoas service-registry rule enable --config none --rule-type validity`
The action should succeed.  Then confirm using:
```
$ rhoas service-registry rule describe --rule-type validity
Fetching global validity rule for artifacts in the Service Registry instance with ID "123xyz"
{
"config": "NONE",
"type": "VALIDITY"
}
```
=> Added a "none" option to the Validity rule config options (Service Registry)

pkg/api/generic/api.go, pkg/api/rbac/api.go, pkg/cmd/request/request.go, pkg/cmd/root/root.go, pkg/shared/connection/api/api.go, pkg/shared/connection/api/defaultapi/default_client.go
Fixes #1494 
Adding number of things to the CLI:
- Ability to call any API without defining it  in the code (was requested by support)
- Adding command for supporting generic api calls with fresh tokens
```
rhoas request --path=/api/kafkas_mgmt/v1/kafkas
```
=> Generic call

pkg/cmd/status/status.go, pkg/cmd/status/statusBuilder.go, pkg/core/localize/locales/en/cmd/status.en.toml, pkg/core/servicecontext/file.go, pkg/shared/contextutil/util.go
I really do think that doing some form of factory object mapping to custom opts structure is total waste of time and doesn't fit much of purpose. Factory is good abstraction on it's own. Removed it from this command specifically.
Added support for name and location
Added common handling for services missing so we can now reuse it.
=> fix: refactor status command

pkg/cmd/context/contextcmdutil/validator.go, pkg/cmd/context/generate/build-configs.go, pkg/cmd/context/generate/configurations.go, pkg/cmd/context/generate/generate-config.go, pkg/core/localize/locales/en/cmd/context.en.toml
Add short description for created service account.
Removed hard coded strings, added flag validation and completion for `--type`.
1. The following command should create a service account with short description with prefix "rhoascli-"
`./rhoas context generate-config --type properties`
2. The following command should throw an error indicating invalid flag value.
`./rhoas context generate-config --type propertiees`
=> fix(context generate-config): remove hard codings

go.mod, go.sum, pkg/cmd/kafka/consumergroup/describe/describe.go, pkg/cmd/kafka/consumergroup/groupcmdutil/util.go, pkg/cmd/kafka/consumergroup/list/list.go
This change uses backend compiled metrics for consumer groups. 
This have been in production for quite a while and have been extensively tested.
1. Get Kafka
2. Create new topic `test`
3. Create kcat.properties based of the kcat guide
4. kcat -b <yourhostname -F ./kcat.properties -P -t test`
5. run rhoas kafka consumer-group list 
6. run rhoas kafka consumer-group describe
=> fix: add server side backed up metrics

pkg/core/localize/locales/en/cmd/context.en.toml, pkg/core/localize/locales/en/cmd/status.en.toml
Edited the command help for the "rhoas context" commands.
I'm not sure about the generate-config command. I tried to include everything that it's potentially supposed to generate, but I'm not sure that all of the functionality is actually in place yet. So we might need to scale back the help text accordingly.
=> docs: edit command help for context commands

pkg/cmd/registry/create/create.go, pkg/cmd/registry/describe/describe.go, pkg/cmd/registry/registrycmdutil/registry_util.go, pkg/core/localize/locales/en/cmd/registry_crud.en.toml
Display compatibility APIs for service registry instances in create an describe command that will be used to connect an application or tool to instances.
1. Run the following command to display compatibility endpoints for the registry instance in current context.
```
rhoas service-registry describe --name my-registry
```
2. Expected output:
```
{
"browserUrl": "https://console.redhat.com/application-services/service-registry/t/c9f1ad77-377c-41f0-baa1-8b9103783893",
"created_at": "2022-02-14T10:47:42Z",
"href": "/api/serviceregistry_mgmt/v1/registries/c9f1ad77-377c-41f0-baa1-8b9103783893",
"id": "c9f1ad77-377c-41f0-baa1-8b9103783893",
"instance_type": "standard",
"kind": "ServiceRegistry",
"name": "enda-dev",
"owner": "ephelan_kafka_devexp",
"registryDeploymentId": 1,
"registryUrl": …
```
=> feat(service-registry): display compatibile API endpoints

docs/commands/rhoas_context.md, docs/commands/rhoas_context_create.md, docs/commands/rhoas_context_set-kafka.md, docs/commands/rhoas_context_set-service-registry.md, pkg/cmd/context/context.go, pkg/cmd/kafka/create/create.go, pkg/core/localize/locales/en/cmd/context.en.toml, pkg/core/localize/locales/en/cmd/status.en.toml
BREAKING CHANGE: rename rhoas context use-<service> to rhoas context set-<service>
Command has been renamed after getting feedbacks.
1. Run the following command to set Kafka instance for the current context
```
rhoas context set-kafka
```
=> refactor(context): rename use-service to set-service

pkg/core/localize/locales/en/cmd/context.en.toml
Improves error message displayed when Kafka Instance set in context doesn't exist.
Current error message:
```
Kafka instance doesn't exist, you must set a valid Kafka instance ID by using the "rhoas context set-kafka" command
```
Changed error message:
```
Kafka instance in your context doesn't exist.
Your instance might have been removed.
You can update your context by creating a new instance or by using the "rhoas context set-kafka" command
``` 
This also keeps it consistent with error message displayed for Service Registry instance.
=> fix(context): improve error message for invalid Kafka instance

docs/commands/rhoas_context.md, docs/commands/rhoas_context_unset.md, pkg/cmd/context/context.go, pkg/cmd/context/unset/unset.go, pkg/cmd/status/status.go, pkg/cmd/status/statusBuilder.go, pkg/core/cmdutil/flagutil/util.go, pkg/core/localize/locales/en/cmd/context.en.toml, pkg/core/localize/locales/en/cmd/status.en.toml, pkg/core/localize/locales/en/common.en.toml
`rhoas context unset` command can be used to unset services in the contexts.
1. Set a Kafka instance in the context using:
```
rhoas context set-kafka
``` 
2. Check the status of the kafka instance. It should print the kafka details
```
rhoas context status kafka
```
3. Unset Kafka instance for the context
```
rhoas context unset --services kafka
```
4. Check status of Kafka instance again, it should throw error.
=> feat(context): add unset command

pkg/cmd/connector/cluster/delete/delete.go, pkg/cmd/connector/delete/delete.go
`rhoas connector cluster delete` was not able to delete the specified ID.
1. Run the following command to delete a connector cluster through ID.
```
rhoas connector cluster delete --id <ID>
```
=> fix(connector cluster): wrong sdk method used in delete cmd

pkg/cmd/kafka/consumergroup/describe/describe.go, pkg/cmd/kafka/consumergroup/list/list.go, pkg/core/localize/locales/en/cmd/kafka.en.toml
The commands `rhoas kafka consumer-group list` and `rhoas kafka consumer-group` describe should display `STATE`.
Describe consumer group:
```
ACTIVE MEMBERS: 0        PARTITIONS WITH LAG: 0 
UNASSIGNED PARTITIONS: 1 STATE: EMPTY
CONSUMER ID   PARTITION   TOPIC    LOG END OFFSET   CURRENT OFFSET   OFFSET LAG  
------------- ----------- -------- ---------------- ---------------- ------------ 
unassigned            0   quotes             1.7K             1.7K            0
```
List consumer groups:
```
CONSUMER GROUP ID                              ACTIVE MEMBERS   PARTITIONS WITH LAG   STATE  
---------------------------------------------- ---------------- --------------------- ------- 
quarkus-service-registry-quickstart-consumer                0                     0   EMPTY 
```
After …
=> feat(consumer-group): display state

go.mod, go.sum
Reverts redhat-developer/app-services-cli#1569 that breaks CLI
=> Revert "fix: update kafka mgmt sdk for the latest version"

pkg/cmd/registry/list/list.go, pkg/shared/serviceregistryutil/interactive.go
Show proper error message for `rhoas service-registry use` when no Service Registry instances are present.
1. Run command to use a Service registry instance when no instance is present.
```
./rhoas context set-service-registry
```
=> fix(service-registry use): erroneous message thrown for no instances

go.mod, go.sum, pkg/cmd/kafka/create/api_validators.go, pkg/cmd/kafka/create/completions.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/create/data.go, pkg/core/localize/locales/en/cmd/kafka.en.toml
Adding warning for size x2 of standard instances (subject to change dynamically in near future)
Warning is displayed only when user specifies size (no default sizes are included)
```
[wtrocki@graphapi app-services-cli (add-warning-kafka-size ✗)]$ rhoas kafka create --name=test --provider=aws --region us-east-1 --dry-run  --size=x2 
Selected Kafka size is available under technology preview
Dry run successful, arguments are valid
[wtrocki@graphapi app-services-cli (add-warning-kafka-size ✗)]$ rhoas kafka create --name=test --provider=aws --region us-east-1 --dry-run  --size=x1 
Dry run successful, arguments are valid
[wtrocki@graphapi app-services-cli (add-warning-kafka-size ✗)]$ 
[wtrocki@graphapi app-services-cli (add-warning-kafka-size)]$ rhoas kafka create --dry-run
? Name: test
? Cloud …
```
=> fix: add tech preview warning

pkg/cmd/registry/create/create.go, pkg/core/localize/locales/en/cmd/registry_crud.en.toml
`rhoas service-registry create` now fetches registry URL and shows correct compatibility endpoints.
Closes #1574 
1. Run the following command to create a registry:
```
rhoas service-registry create
```
2. You should be able to see the registry URL along with compatibility endpoints once creation is successful.
=> fix(service-registry create): fetch registry URL after creation

pkg/cmd/kafka/topic/delete/delete.go, pkg/core/localize/locales/en/cmd/kafka.en.toml
The prompt the user gets when confirming the deletion of a topic now also contains the name of that topic.
When topic name is `prices`
Before:
```
Confirm the name of the topic you want to delete: 
```
Now:
```
Confirm the name of the topic you want to delete (prices): 
```
1. Clone repo and checkout branch `topic-delete-prompt-change`
2. `go run ./cmd/rhoas kafka topic delete --name prices`
3. Confirm prompt is `Confirm the name of the topic you want to delete (prices): `
=> Added topic name as a hint when confirming deletion of topic

docs/commands/rhoas_service-account_create.md, docs/commands/rhoas_service-account_reset-credentials.md, pkg/core/localize/locales/en/cmd/serviceaccount.en.toml, pkg/core/localize/locales/en/cmd/serviceaccount_create.en.toml, pkg/core/localize/locales/en/cmd/serviceaccount_reset_credentials.en.toml
Help texts for `service-account` commands didn't show "secret" as a valid file format in multiple places.
1. Descriptions for the command `rhoas service-account create` and `rhoas service-account reset-credentials` should mention "secret" along with other valid file formats for output.
=> docs(service-account): add secret option to file format descriptions

docs/commands/rhoas_generate-config.md, pkg/core/localize/locales/en/cmd/generate_config.en.toml
Added text to describe supported file formats supported by `rhoas generate-config`. It is similar to what we have for `rhoas service-account create`.
1. Run the following command to see the description and help text of `generate-config`. It should explain each of the file format supported:
```
./rhoas generate-config -h
```
=> docs(generate-config): show valid output types in examples

pkg/cmd/kafka/create/create.go, pkg/core/localize/locales/en/cmd/kafka.en.toml
Do not call AMS when using upstream version of the platform/Self installed.
Non interactive:
rhoas kafka create --dry-run --bypass-checks --name=test -v
Dry run successful, arguments are valid 
Interactive mode:
[wtrocki@graphapi app-services-cli (ski-ams-check ✗)]$ rhoas kafka create --dry-run --bypass-checks
❌ Interactive mode is not supported when using --skip-checks flag. Run the command in verbose mode using the -v flag to see more information
=> fix: add bypass for ams for kas-installer

pkg/cmd/kafka/create/completions.go, pkg/cmd/kafka/create/create.go, pkg/core/localize/locales/en/cmd/kafka.en.toml, pkg/shared/accountmgmtutil/ams.go
Completion and validation of cloud account IDs should take care of the cloud_provider wherever possible.
1. Run `rhoas kafka create` in interactive mode.
2. Selecting marketplace should show Account IDs for that marketplace only.
=> fix(kafka create): completions should consider provider

pkg/shared/connection/api/defaultapi/default_client.go
Before
```
Making request to https://admin-server-tesaddstas-calbu-ccff-bdd-jsg-a.kas.mk-cakn1ba87d5o.1e0z.s1.devshift.org
2022/06/16 09:13:53 
GET //api/v1/topics?page=1&size=10 HTTP/1.1
Host: admin-server-tesaddstas-calbu-ccff-bdd-jsg-a.kas.mk-cakn1ba87d5o.1e0z.s1.devshift.org
User-Agent: rhoas-cli_dev
Accept: application/json
Accept-Encoding: gzip
```
After
```
Making request to https://admin-server-tesaddstas-calbu-ccff-bdd-jsg-a.kas.mk-cakn1ba87d5o.1e0z.s1.devshift.org
2022/06/16 09:13:53 
GET /api/v1/topics?page=1&size=10 HTTP/1.1
Host: admin-server-tesaddstas-calbu-ccff-bdd-jsg-a.kas.mk-cakn1ba87d5o.1e0z.s1.devshift.org
User-Agent: rhoas-cli_dev
Accept: application/json
Accept-Encoding: gzip
```
=> fix: remove redundant kafka admin slash

pkg/shared/connection/api/defaultapi/default_client.go
Hardcoded url that was used were matching only production. For any other env url can have different format. We should always use control plane kafka response in all tooling.
=> fix: use kafka admin url from control plane

pkg/core/localize/locales/en/cmd/kafka.en.toml, pkg/shared/hacks/temp.go
Enable using env var to override behaviour for fetching sso providers
```
RHOAS_CUSTOM_SSO_PROVIDER_URL ="https://gist.githubusercontent.com/wtrocki/6eed975bf32e5de9ec68f16f59f819e0/raw/38052cf5c2eafd17d86a5a54e5d80a0e10a5bc81/sso_provider.json" rhoas service-registry artifact list
```
=> Custom provider

docs/commands/rhoas_generate-config.md, pkg/cmd/generate/build-configs.go, pkg/cmd/generate/configurations.go, pkg/cmd/generate/generate-config.go, pkg/core/localize/locales/en/cmd/generate_config.en.toml
The default file to save configuration details in environment variables has been changed from `rhoas.env` to `.env`
A `--overwrite` flag has been added to warn of already existing file.
1. The following command should save connection configurations in a `.env` file:
```
rhoas generate-config --type env
```
2. Running the command again should throw the following error:
```
File `.env` already exists. Use --overwrite to overwrite the file, or the --output-file flag to choose a different location.
```
3. The existing file can be overridden using the `--overwrite` flag.
```
rhoas generate-config --type env --overwrite
```
=> feat(generate-config): add overwrite flag and change default env file

.github/workflows/modular-docs-publish.yml
Point here is to make sync of the documentation also on prereleases so we can include content downstream faster and give time to adapt the changes. 
CLI is released slowly right now (once per month).
Problem with this is that synced changes would reflect future versions of CLI so they never can be merged. I'm not sure if we want that.
=> fix: add prerelease support for documentation sync

pkg/cmd/kafka/topic/consume/consume.go, pkg/core/localize/locales/en/cmd/kafka.en.toml
Removes the old --from and --unix flags to separate time into two commands. Also updated examples to reflect this change in the API.
1. `rhoas kafka topic consume --name=topic --format=json --offset=1` should work normal
2. `rhoas kafka topic consume --name=topic --wait` should work normal with time being the current, any new messages should be seen here.
3. `rhoas kafka topic consume --name=topic --from-date=2021-01-01T01:01:01.0000Z --wait` any messages you created passed this time should be displayed
4. `rhoas kafka topic consume --name=topic --from-timestamp=290384 --wait` any messages you created passed this time should be displayed
5. `rhoas kafka topic consume --name=topic --from-timestamp=290384 --from-date=2021-01-01T01:01:01.0000Z` should give you an error as you are setting …
=> Consume now uses separate time flags for date and Unix

docs/commands/rhoas.md, docs/commands/rhoas_completion.md, docs/commands/rhoas_completion_bash.md, docs/commands/rhoas_completion_fish.md, docs/commands/rhoas_completion_powershell.md, pkg/cmd/completion/completion.go, pkg/cmd/completion/powershell/powershell.go, pkg/core/localize/locales/en/cmd/completion.en.toml
The rhoas completion command instructions to enable command completions Powershell as well.
Closes #1595
=> feat(completion): add instruction for powershell completions

pkg/cmd/kafka/topic/consume/consume.go
Fixes bug where the cli was trying to get the value of a key when the message did not have one
=> fix: nil keys are now empty strings when consumed

docs/commands/rhoas_connector_cluster_create.md, pkg/core/localize/locales/en/cmd/connectors.toml
You need to be an org administrator to create a cluster for connectors. This was not documented before.
=> docs: included info about org admin for connector cluster create

pkg/shared/factory/defaultfactory/default.go
This PR disables connection reuse. 
In previous change I have noticed that we always refresh mas-sso tokens even when we do control plane commands only:
https://github.com/redhat-developer/app-services-cli/pull/1599/files
That would obviously cause problems in long term and was removed. As results we noticed 401 with tokens failing. Reason was that we had cache for connection function that was undocumented. I think we should disable this cache. This will create connection object couple times for 2-3 commands but overall it doesn't cause any extra problems and enables us to mix mas-sso commands
Note that mas-sso goes away so this is only temporary change anyway.
```
// wait 5 min after any command
rhoas kafka topic list
```
=> fix: do not reuse connection for the commands

CONTRIBUTING.md, cmd/rhoas/main.go, pkg/cmd/login/login.go, pkg/core/auth/token/token.go, pkg/core/cmdutil/profile/profile.go, pkg/core/localize/locales/en/cmd/login.en.toml
This fixes problems with offline tokens/refresh tokens when having empty config. I think we should use empty config flag for testing etc. 
```
RHOASCONFIG="./config.json" rhoas login
RHOASCONFIG="./config.json" rhoas login --token
RHOASCONFIG="./config.json" rhoas login
```
Notice token login not printing user info but classic login does
Check how config changes when testing
=> fix: add env var config

docs/commands/rhoas_kafka_create.md, go.mod, go.sum, pkg/cmd/kafka/create/api_validators.go, pkg/cmd/kafka/create/completions.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/create/data.go, pkg/core/localize/locales/en/cmd/kafka.en.toml, pkg/shared/accountmgmtutil/ams.go, pkg/shared/accountmgmtutil/api.go
This PR adds `--billing-model` flag to `rhoas kafka create` command.
The CLI should be able to create instances with standard, marketplace and trial quotas. 
1. For testing against marketplace  (use _kafka_service account).
`rhoas kafka create --name test-instance` should throw error saying multiple quota types are available and user needs to specify billing model.
`rhoas kafka create --name test-instance --billing-model standard` should create a standard instance
`rhoas kafka create --name test-instance --billing-model standard` should create a marketplace instance
`rhoas kafka create` should start the creation in interactive mode and prompt for billing model.
User should be able to pick marketplace provider and market place account if multiple options are available, else the only …
=> feat(kafka create): add billing model logic

pkg/shared/factory/defaultfactory/default.go
Reverting https://github.com/redhat-developer/app-services-cli/pull/1624/files
This change was to ensure that we mas-sso tokens refresh have been added. Now since mas-sso tokens are gone we should cache our regular sso tokens across session.
This is still not perfect but due to very large amount of connections created in various helpers (kafka create creates -7 connections on it's own - that is 7 sso refreshes per command). Some better refactor for connection objects is needed.
For now we can cache that object as there is no chance that tokens will outdate during single command run (5minutes)
=> fix: cache connection to skip refreshes

pkg/cmd/kafka/topic/consume/consume.go, pkg/core/localize/locales/en/cmd/kafka.en.toml
Closes # 
1. Create a kafka with 2 topics
2. run `rhoas kafka topic consume --name=topic --partition=0 --wait`
3. Then in another terminal produce to the same topic `rhoas kafka topic produce --name=topic --partition=0`
4. You should the messages come in
5. Try and produce a message on a different topic and no messages should appear
6. Repeat for each topic
7. Run  `rhoas kafka topic consume --name=topic --wait` should not work
=> fix: can now only consume and wait from single topic

pkg/cmd/generate/build-configs.go, pkg/cmd/generate/configurations.go, pkg/core/localize/locales/en/cmd/generate_config.en.toml
`rhoas generate-config` should now print the file to which the configurations have been saved to. This had been one of the PM feedback for the `generate-config` command.
1. Run the following command to save configurations in `config.json`
```
./rhoas generate-config --type json --output-file "config.json"
```
2. It should log the following message:
```
✔️  Configurations successfully saved to "config.json"
```
=> fix(generate-config): print path to configuration file

pkg/shared/cluster/bind.go
We should include user preference for binding as files.
Fixes https://github.com/redhat-developer/app-services-cli/issues/1665
Typical minikube verification applies
=> fix: include bind as files flag into CR creation

docs/commands/rhoas_context_unset.md, pkg/cmd/context/unset/unset.go, pkg/cmd/generate/build-configs.go, pkg/core/localize/locales/en/cmd/generate_config.en.toml
Flag description for `context unset` command used the key rather than getting the corresponding value through localizations.
The following command should display proper flag descriptions:
```
rhoas context unset -h
```
=> docs(context unset): erroneous flag description

docs/commands/rhoas_connector_type_list.md, pkg/cmd/connector/connector_type/list/list.go, pkg/core/localize/locales/en/cmd/connectors.toml
Closes # 
Before the page and limit flag in `rhoas connector type list` has the same description. This pr fixes that and gives a better description of the page flag aswell
1. Use auto suggest in your shell to see the description of page and limit are no longer the same
=> Fixing page and limit had same description in connector type list

pkg/cmd/generate/configurations.go, pkg/core/localize/locales/en/cmd/generate_config.en.toml
This is a follow up to #1588 .
The PR updates the success message printed after configs are generated.
`rhoas generate-config --type env` should save configurations to `rhoas.env`
1. Run the following command:
```
./rhoas generate-config --type env
```
2. The command should save configurations in `rhoas.env`.
```
Configurations successfully saved to "/home/rkpattnaik780/coding/redhat/mk/cli/rhoas.env"
You can now use existing service accounts or create new to connect to the services.
To create new service account, run this command:
$ rhoas service-account create
```
=> fix(generate-config): update success message and default path for env

docs/commands/rhoas_service-registry.md, docs/commands/rhoas_service-registry_setting.md, docs/commands/rhoas_service-registry_setting_get.md, docs/commands/rhoas_service-registry_setting_list.md, docs/commands/rhoas_service-registry_setting_set.md, pkg/cmd/registry/registry.go, pkg/cmd/registry/setting/get/get.go, pkg/cmd/registry/setting/list/list.go, pkg/cmd/registry/setting/set/set.go, pkg/cmd/registry/setting/setting.go, pkg/core/localize/locales/en/cmd/setting.en.toml
This PR adds new setting command group with three subcommands:
list : List current configuration settings
set : Set the value of a configuration setting
get: Get the value of a configuration setting
Closes #1650
```
$ rhoas service-registry setting list
```
```
$ rhoas service-registry setting set --setting-name registry.ccompat.legacy-id-mode.enabled --value true
```
Also, in registry there is an option to reset setting to default value, to do this using cli tool you can use a set command:
```
$ rhoas service-registry setting set --setting-name registry.ccompat.legacy-id-mode.enabled --default
```
From the original proposal I have added also get command to get ConfigurationProperty of specific name.
```
$ rhoas service-registry setting get --setting-name …
```
=> WIP: feat(service-registry): setting command

pkg/cmd/connector/create/create.go, pkg/shared/contextutil/util.go
Connector create now uses context to get values for kafka and namespace.
1. Do x
2. Do y
=> Context in connector create

docs/commands/rhoas_kafka.md, docs/commands/rhoas_kafka_update.md, pkg/core/localize/locales/en/cmd/kafka_update.en.toml
As I'm writing the doc for the new re-authenticate connection setting in the web console UI, I updated the CLI help text to match.
=> Doc: update command help for kafka instance settings

docs/commands/rhoas_service-registry_setting.md, pkg/core/localize/locales/en/cmd/setting.en.toml
Document `registry.auth.authenticated-read-access.enabled` setting 
(i.e., instead of `registry.auth.owner-only-authorization.limit-group-access`, which is an Apicurio-only setting)
=> docs: fix list of available service registry settings

docs/commands/rhoas_login.md, pkg/cmd/login/login.go, pkg/core/localize/locales/en/cmd/login.en.toml, pkg/shared/connection/kcconnection/errors.go
URL is no longer valid and have been included in +2 releases as deprecated. We can remove it
=> fix: remove mas-auth  url

pkg/cmd/connector/connector_type/list/list.go, pkg/core/localize/locales/en/cmd/connectors.toml
Adds some info on the output of connector type list on where the current list is in relation to the pages.
Before
```
.
.
.
{
"name": "Apache Cassandra sink",
"id": "cassandra_sink_0.1",
"description": "Send data to an Apache Cassandra cluster."
}
{
"name": "Apache Cassandra source",
"id": "cassandra_source_0.1",
"description": "Retrieve data by sending a query to an Apache Cassandra cluster table."
}
{
"name": "Azure Blob Storage change feed source",
"id": "azure_storage_blob_changefeed_source_0.1",
"description": "Receive data from Azure Blob storage change feed."
}
{
"name": "Azure Blob Storage sink",
"id": "azure_storage_blob_sink_0.1",
"description": "Send data to Azure Blob storage."
}
{
"name": "Azure Blob Storage source",
"id": "azure_storage_blob_source_0.1",
"description": …
```
=> feat: added info on pageination in type list

docs/commands/rhoas_connector.md, docs/commands/rhoas_connector_build.md, docs/commands/rhoas_connector_create.md, docs/commands/rhoas_connector_describe.md, docs/commands/rhoas_connector_update.md, pkg/cmd/connector/build/build.go, pkg/cmd/connector/connector.go, pkg/cmd/connector/create/create.go, pkg/cmd/connector/delete/delete.go, pkg/cmd/connector/describe/describe.go, pkg/cmd/connector/update/update.go
This PR makes the new connectors command that were added in the last release not hidden.
1. Enter `rhoas connector` and use TAB for auto suggestions, you will be prompt with a list. Verify options such as `create`, `build` are there.
=> feat: new connector commands are now not hidden

docs/commands/rhoas_kafka.md, docs/commands/rhoas_kafka_billing.md, docs/commands/rhoas_kafka_providers.md, pkg/cmd/kafka/billing/billing.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/create/data.go, pkg/cmd/kafka/kafka.go, pkg/cmd/kafka/providers/providers.go, pkg/core/localize/locales/en/cmd/kafka.en.toml
Enable users to fetch state for their organization and personal account required for kafka creation.
This approach enables granular set of commands that can be useful for users to get information about where kafka is deployed and how they are billed by creating kafka.  
```
[wtrocki@graphapi app-services-cli (supporting-gitops)]$ rhoas kafka providers 
CLOUD PROVIDER   REGION     
---------------- ----------- 
aws              eu-west-1  
aws              us-east-1  
```
This command fetching billing information - We need to extend this by including plans etc.
Depends on @rkpattnaik780 investigation on how we can represent all of that in gitops setup.
```
[wtrocki@graphapi app-services-cli (supporting-gitops ✗)]$ rhoas kafka billing
BILLING    
----------- 
developer  
```
=> Supporting gitops

pkg/core/servicecontext/file.go
As today, it a custom context file is set, then the code check for the existence of the context file and fails if it does not exist, however, this is not true for custom configuration location. This PR aims to make config and context behaving consistently. 
1. Set `RHOASCONFIG` to an not existing file
2. Run `rhoas`
3. No error should be reported and the `RHOASCONFIG` file should have been created
=> feat: do not check for context existence if a custom context file is set

docs/commands/rhoas.md, docs/commands/rhoas_request.md, pkg/cmd/request/request.go
When chatting with @dimakis we seen that request command is not public. adding this as PR instead of issue as change is trivial
=> fix: make request command public

pkg/core/localize/locales/en/cmd/context.en.toml, pkg/shared/contextutil/util.go
This commit improves the error handling in case the namespace is not found. It returns more detailed message rather than just returning the error.
Fixes: #1738
Signed-off-by: yati1998 <ypadia@redhat.com>
=> error: return detailed error message for ns not found

docs/commands/rhoas_service-registry_artifact_export.md, pkg/core/localize/locales/en/cmd/artifact.en.toml
The current export command text is not aligned with the real flags used by the command.
The command requires to use `output-file` however the help sais to use `file` flag.
1. Display the export help: `rhoas service-registry artifact export --help' 
2. Execute the export: `rhoas service-registry artifact export --output-file=export.zip`
3. 
- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Other (please specify)
=> fix(documentation): Use right flags for export command

website/README.md
This PR includes a small fix of the documentation to start locally the website documentation. It is related with the #1777 issue.
(Could) Closes #1777 
1. Follow instructions from README.md file
=> fix(documentation) How to start locally the website

docs/commands/rhoas_request.md, pkg/cmd/request/request.go, pkg/core/localize/locales/en/cmd/request.en.toml
=> Localize strings in request command

pkg/cmd/connector/cluster/create/create.go
fixes an issue with `connector cluster create` command:
```
rhoas connector cluster create --name=test
Successfully created the Connectors cluster named "<no value>"
```
=> fix(connector): add missing name in the log

internal/build/build.go, pkg/core/cmdutil/selfupdate.go
This PR will ensure that a check for auto-update is made only for binaries built via GitHub.
1. Build the binary locally with the following command:
```
go build  -ldflags "-X github.com/redhat-developer/app-services-cli/internal/build.SSORedirectPath="sso-redhat-callback" -X github.com/redhat-developer/app-services-cli/internal/build.DefaultPageNumber="1" -X github.com/redhat-developer/app-services-cli/internal/build.DefaultPageSize="10" -X github.com/redhat-developer/app-services-cli/internal/build.DynamicConfigURL="https://console.redhat.com/apps/application-services/service-constants.json" -X github.com/redhat-developer/app-services-cli/internal/build.RepositoryName="app-services-cli" -X github.com/redhat-developer/app-services-cli/internal/build.RepositoryOwner="redhat-developer" -X …
```
=> chore(release): disable auto-updates for non-github binaries

pkg/cmd/kafka/create/create.go, pkg/core/localize/locales/en/cmd/kafka.en.toml
1. Create Kafka instance for user with standard quota selecting gcp as the provider.
```
./rhoas kafka create --dry-run -v
```
It should fail showing `All regions in the selected cloud provider are temporarily unavailable`
2. Run the command above with a user having no quota. Creation should succeed when gcp is selected as  the cloud provider.
=> feat(kafka create): return appropriate error for no regions

pkg/cmd/kafka/create/completions.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/create/data.go, pkg/core/localize/locales/en/cmd/kafka.en.toml, pkg/shared/accountmgmtutil/ams.go
Selection of marketplace provider should be dependent on the cloud provider.
1. Use mock server.
2. Run Kafka create in interactive mode. User should not be able to select `gcp` as marketplace when `aws` is chosen as the cloud provider:
```
rhoas kafka create --dry-run -v
```
=> fix(kafka create): sync marketplace provider with cloud provider

docs/commands/rhoas_connector_update.md, pkg/cmd/connector/create/create.go, pkg/cmd/connector/update/update.go, pkg/core/localize/locales/en/cmd/connectors.toml
Closes # 
1. Run the following command to update a connector instance by id:
```
rhoas connector update --kafka-id ce6pg07k09f3rs6us7sg --id ce6tgb1mk0orirpo5i70
```
2. Ensure that the connectors instance has been updated, and the new Kafka URL has been specified.
=> fix(connector update): populate kafka url

docs/commands/rhoas_connector_update.md, pkg/cmd/connector/update/update.go, pkg/core/localize/locales/en/cmd/connectors.toml
BREAKING: namespace flag has been deprecated
=> fix(connector update): remove namespace flag

pkg/cmd/connector/describe/describe.go, pkg/cmd/connector/list/list.go, pkg/cmd/connector/namespace/list/list.go
The commands `rhoas connector describe`, `rhoas connector list` and `rhoas connector namespace list` now reflect the instance set in the current context.
1. Select a connector instance:
```
rhoas connector use
```
2. List the Connector instances in the org, it should show the connectors instance set in the current context
```
rhoas connector list
```
3. View the connector instance currently set in the context.
```
rhoas connector describe
```
4. Select a connector namespace:
```
rhoas connector namespace use
```
5. List all connector namespaces, it should show the namespace set in the current context
```
rhoas connector namespace list
```
=> feat(connector): load current context for commands

docs/commands/rhoas_kafka_create.md, pkg/cmd/kafka/create/api_validators.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/create/data.go, pkg/core/localize/locales/en/cmd/kafka.en.toml, pkg/shared/accountmgmtutil/ams.go, pkg/shared/accountmgmtutil/api.go, pkg/shared/remote/DynamicServiceConstants.go, pkg/shared/remote/service-constants.json
Add additional billing model `eval` to create long lived trial instances.
1. Create a local binary of the CLI:
```
make binary
```
2. Login to an org having quotas for long lived trial instances
```
rhoas login --api-gateway staging
```
3. Run kafka create command setting `eval` as billing model
```
./rhoas kafka create --name test-instance --billing-model eval --dry-run -v
```
4. The logs should show that the selected quota object with name "eval".
5. Request body should have billing model "eval".
=> feat(kafka create): enable creating long-lived trial instances

pkg/cmd/dedicated/register/registercluster.go
This is so that "apps." prefix is always included and required by KFM when it is running under certain configuration
Related to https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/issues/266#issuecomment-1424156487
1. `make binary`
2. `./rhoas dedicated register-cluster  -v` and observe that the KFM cluster registration payload now contains a valid `cluster_ingress_dns_name` field i.e with `apps.` prefix in it.
- ~~[ ] New feature (non-breaking change which adds functionality)~~
- ~~[ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)~~
- ~~[ ] Documentation change~~
- ~~[ ] Other (please specify)~~
=> fix(dedicated): attempts to correctly parse the cluster ingress dns name

go.mod, go.sum, vendor/github.com/jackdelahunt/survey-json-schema/pkg/surveyjson/schema_type.go, vendor/github.com/jackdelahunt/survey-json-schema/pkg/surveyjson/survey.go, vendor/modules.txt
Changes already verified here -> https://github.com/jackdelahunt/survey-json-schema/pull/18
1. `rhoas connector build --type=telegram_sink_0.1`
2. Can now select type of `telegram_authorization_token`
=> feat: updated json schema library

pkg/cmd/kafka/delete/delete.go, pkg/cmd/kafka/describe/describe.go, pkg/cmd/registry/delete/delete.go, pkg/cmd/registry/describe/describe.go
Adresses #1522 
1. Run Service Registry describe command in verbose mode:
```
rhoas service-registry describe -v
```
2. It should call the endpoint `api/serviceregistry_mgmt/v1/registries/<registry-id>` only once.
=> refactor: override fetch if instance exists

pkg/cmd/dedicated/listclusters/list.go, pkg/cmd/kafka/create/create.go, pkg/core/localize/locales/en/cmd/kafka.en.toml, pkg/shared/kafkautil/dedicated_utils.go
=> Enterprise crete kafka interactive

pkg/cmd/dedicated/listclusters/list.go, pkg/shared/kafkautil/dedicated_utils.go
Moving this out for easy resuse
Closes # 
1. Do x
2. Do y
=> refactor: moving list enterprise clusters to util package

pkg/cmd/dedicated/listclusters/list.go, pkg/cmd/dedicated/listclusters/list_test.go, pkg/cmd/kafka/create/create.go, pkg/cmd/kafka/create/data.go, pkg/core/localize/locales/en/cmd/dedicated.en.toml, pkg/core/localize/locales/en/cmd/kafka.en.toml, pkg/shared/accountmgmtutil/ams.go, pkg/shared/kafkautil/dedicated_utils.go, pkg/shared/remote/DynamicServiceConstants.go, pkg/shared/remote/service-constants.json
Some refactoring of the create kafka cmd.
interactive prompt for cluster selection now shows name and ID. 
flags still need to be updated i.e. if flags are passed skip the interactive logic
1. Do x
2. Do y
=> Enterprise create kafka interactive refactor2

docs/commands/rhoas.md, docs/commands/rhoas_dedicated.md, docs/commands/rhoas_dedicated_deregister-cluster.md, docs/commands/rhoas_dedicated_list.md, docs/commands/rhoas_dedicated_register-cluster.md, docs/commands/rhoas_kafka_list.md, pkg/cmd/dedicated/dedicated.go, pkg/cmd/dedicated/dedicatedcmdutil/dedicated_util.go, pkg/cmd/dedicated/deregister/deregister.go, pkg/cmd/dedicated/list/list.go, pkg/cmd/dedicated/list/list_test.go, pkg/cmd/dedicated/listclusters/list.go, pkg/cmd/dedicated/register/registercluster.go, pkg/cmd/kafka/create/create.go, pkg/core/localize/locales/en/cmd/dedicated.en.toml, pkg/core/localize/locales/en/cmd/kafka.en.toml, pkg/shared/accountmgmtutil/ams.go
- Updates the CLI to display cluster ID and Name for `register-cluster`, `deregister-cluster` 
- adds the `cluster-mgmt-api-url` and `access-token` flags to `kafka create`
- fixes typos and implements better wording
- addresses some comments brought up in the sprint review demo
1. Register an OpenShift cluster
2. Create Kafka clusters interactively
3. Deregister Hybrid OpenShift clusters
=> Add clustermgmt flag to create kafka

pkg/cmd/kafka/create/create.go
When user is selecting to use the new RHOSAK flow or the legacy flow, the order in which they are displayed are inverted. Meaning the new "default" flow is the top option.
1. Using an account that has access to both legacy and enterprise run `rhoas kafka create`
2. You will be promoted to select either flow
3. The new flow will now be the first option
=> refactor: enterprise option is now first in prompt
